// Position drafts are scoped to the asset and kept only in this page session.
const positionDrafts=new Map();
function restorePositionInputs(symbol){const p=positionDrafts.get(symbol)||{qty:'0',cost:'0'};$('heldQty').value=p.qty;$('heldCost').value=p.cost;}
function rememberPositionInputs(){if(current)positionDrafts.set(current,{qty:$('heldQty').value,cost:$('heldCost').value});}
function renderEnginePanel(x){
 const host=$('enginePanel');if(!host||!x)return;const e=x.engine,p=e.plan,price=v=>formatPrice(current,v),pct=v=>Number.isFinite(v)?fmt(v*100,2)+'%':'—';
 const evidence=engineEvidence(x);
 const risk=Number($('riskPct').value),allocation=Number($('allocationPct').value),capital=Number($('capital').value),stock=STOCKS.includes(current),fx=unit(current)==='USD'?calc('USDTRY'):null;
 const fxRate=unit(current)==='USD'?(fx?.fresh?fx.last.c:null):1;
 const sized=stock&&p&&e.tradable?AnalysisEngine.sizePosition(p,capital,risk,allocation,fxRate):{quantity:0,estimatedRisk:0,amount:0};
 host.innerHTML=`<div class="engineHead"><div><span class="eyebrow">ANALİZ MOTORU ${esc(e.version)}</span><h3>${esc(e.setup)}</h3><p>${esc(e.action)}</p></div><span class="statusPill ${e.positive?'isBuy':e.style==='reduce'?'isSell':'isWait'}">${e.quality.provisional?'Mum tamamlanmadı':esc(dateText(x.last.date))}</span></div>
 <p class="engineEvidence">${esc(evidence)}</p><div class="engineMetrics">${[['Piyasa',e.market?.regime||'Veri sınırlı'],['Emsale göre 20G',Number.isFinite(e.indicators?.relative20)?fmt(e.indicators.relative20,1)+' yüzde puan':'—'],['ADX trend kuvveti',num(e.indicators?.adx)],['Haftalık teyit',e.weekly?.label||'—']].map(([a,b])=>`<div><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('')}</div>
 ${p?`<h4>Giriş ve çıkış senaryosu</h4><div class="engineMetrics">${[['Örnek giriş bölgesi',price(p.entryLow)+' – '+price(p.entryHigh)],['Geçersizlik / stop',price(p.stop)],['İlk hedef / engel',price(p.target)],['Maliyet sonrası getiri/risk',fmt(p.rr,2)+' R']].map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('')}</div><p class="sourceNote">Hedef, yakın direnç veya 2R mesafesidir; fiyat tahmini değildir. Tek yön komisyon + kayma varsayımı %${fmt(p.costBps/100,2)}. Stop fiyat boşluğunda daha kötü gerçekleşebilir. Plan günlük mum fiyatına dayanır; üstteki son fiyat farklı olabilir.</p><p class="bodyText">${p.available?'Koşullar uygunsa plan incelenebilir.':'Mevcut evrede yeni giriş planı etkin değil.'} ${e.tradable?'Maliyet sonrası en az 1,5R ve veri koşulları sağlanıyor.':'İşleme uygunluk için tamamlanmış mum, yeterli hacim verisi ve en az 1,5R gerekiyor.'}</p>`:''}
 <details class="appleDisclosure"><summary>Lehte kanıtlar ve karşı senaryo</summary><ul>${e.reasons.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><h4>Karşı kanıtlar</h4><ul>${e.risks.map(t=>`<li>${esc(t)}</li>`).join('')||'<li>Ek risk bayrağı bulunmadı; bu risksiz işlem anlamına gelmez.</li>'}</ul><p>${esc(e.change||'Geçerli veri gerekli.')}</p></details>`;
 set('engineSizing',stock?`${sized.quantity} lot · yaklaşık ${fmt(sized.amount)} TL kullanım · stop ve varsayılan maliyetle ${fmt(sized.estimatedRisk)} TL risk. ${e.tradable?'':'Plan koşulları uygun olmadığı için miktar sıfır.'}`:'Otomatik lot hesabı yalnız BIST hisseleri içindir; emtia ve döviz sözleşme büyüklükleri modellenmiyor.');
 const heldQty=Math.max(0,Number($('heldQty').value)||0),heldCost=Math.max(0,Number($('heldCost').value)||0);
 set('positionReading',heldQty&&heldCost?`Girdiğin pozisyon: ${fmt(heldQty,0)} adet · maliyet ${price(heldCost)} · günlük mum fiyatıyla brüt fark ${price(heldQty*(x.last.c-heldCost))}. ${!e.quality.usable?'Güncel veri olmadığından çıkış değerlendirmesi yapılamıyor.':e.setup==='ZAYIF TREND'||e.setup==='BAŞARISIZ KIRILIM'?'Çıkış incelemesi: trend zayıflıyor; aşağıdaki geçersizlik seviyesini ve kendi zarar sınırını kontrol et.':p?`İzlenen geçersizlik ${price(p.stop)}; günlük kapanış altında kalıcılık planın yeniden değerlendirilmesini gerektirir.`:''}`:'Pozisyonun varsa adet ve ortalama maliyeti gir. Zayıf görünüm, elinde olmayan hissede otomatik satış emri anlamına gelmez.');
 const report=window.ANALYSIS_REPORT,record=report?.assets?.[current],valid=report?.version===AnalysisEngine.VERSION&&record?.signature===AnalysisEngine.fingerprint(x.a);
 const reportHost=$('engineBacktest');
 if(!valid||record.error){reportHost.innerHTML='<h3>Geçmiş işlem ölçümü</h3><p>Bu motor sürümü ve fiyat serisi için eşleşen rapor yok. Veri yenileme iş akışı yeni raporu üretir.</p>';return;}
 const metric=(title,s)=>`<div class="engineTestBlock"><h4>${title}</h4><p>${dateText(s.startDate)} – ${dateText(s.endDate)}</p><div class="engineMetrics">${[['İşlem sayısı',s.count],['Kazanan işlemler',pct(s.winRate)],['İşlem başına net ortalama',pct(s.meanReturn)],['Kâr / zarar toplamı',s.profitFactor===null?'—':fmt(s.profitFactor,2)]].map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('')}</div><p class="sourceNote">${s.count<30?'30’dan az işlem: örneklem sınırlı.':'İşlemler bağımsız değildir; oran başarı olasılığı olarak kullanılamaz.'}</p></div>`;
 reportHost.innerHTML=`<h3>Geçmişte bu plan ne yaptı?</h3><p>Fiyat paketi: ${esc(timeText(report.snapshotAt))} · testin son tamamlanmış barı: ${dateText(record.lastDate)}</p>${metric('Tüm kullanılabilir dönem',record.full)}${metric('Son %30 tarih aralığı',record.later)}<p>Son dönem maliyeti ikiye katlandığında işlem başına ortalama: <b>${pct(record.stress.meanReturn)}</b> (${record.stress.count} işlem). Aynı dönemde alıp tutma karşılaştırması: <b>${pct(record.buyHoldLater)}</b>. Sermayenin piyasada kaldığı süreler farklıdır.</p><details class="appleDisclosure"><summary>Varsayımlar ve sınırlar</summary><ul>${report.assumptions.map(s=>`<li>${esc(s)}</li>`).join('')}</ul><p>Kapanmış işlemlerle bileşik getiri: ${pct(record.later.compoundedReturn)}; kapanmış işlem serisinin en büyük gerilemesi: ${pct(record.later.closedTradeDrawdown)}. Bunlar gün içi / günlük portföy riskini ölçmez.</p></details><details class="appleDisclosure"><summary>Son 12 örnek işlem</summary><div class="engineTrades"><table><thead><tr><th>Sinyal</th><th>Giriş</th><th>Çıkış</th><th>Net sonuç</th><th>Neden</th></tr></thead><tbody>${record.full.trades.slice(-12).reverse().map(t=>`<tr><td>${esc(t.signalDate)}</td><td>${esc(t.entryDate)}<br>${price(t.entry)}</td><td>${esc(t.exitDate)}<br>${price(t.exit)}</td><td>${pct(t.netReturn)}</td><td>${esc(({stop:'Stop',target:'Hedef','stop-gap':'Stop altı açılış','target-gap':'Hedef üstü açılış','same-bar-stop-first':'Aynı mum: stop önce',time:'10 bar','period-end':'Dönem sonu'})[t.reason]||t.reason)}</td></tr>`).join('')}</tbody></table></div></details>`;
}
function engineEvidence(x){
 const report=window.ANALYSIS_REPORT,record=report?.assets?.[current];
 if(!record||report.version!==AnalysisEngine.VERSION||record.signature!==AnalysisEngine.fingerprint(x.a))return 'Bu fiyat serisine ait geçmiş ölçüm yok; motor deneysel.';
 const result=record.later;
 if(!result?.count)return 'Son tarih aralığında işlem örneği yok; strateji doğrulanmış değil.';
 if(result.meanReturn<=0)return `Geçmiş ölçüm olumsuz: son aralıkta ${result.count} işlem, işlem başına net ortalama %${fmt(result.meanReturn*100,2)}. Bu model kârlı strateji olarak doğrulanmadı.`;
 return `Son tarih aralığında ${result.count} işlemde net ortalama %${fmt(result.meanReturn*100,2)}. ${result.count<30?'Örneklem sınırlı. ':''}Bu geriye dönük sonuç bağımsız ileri test değildir.`;
}
function engineHomeSummary(readings){
 const eligible=readings.filter(r=>r.x?.engine?.quality.usable),ready=eligible.filter(r=>r.x.engine.tradable),preview=eligible.filter(r=>r.x.engine.positive&&r.x.engine.quality.provisional),report=window.ANALYSIS_REPORT;
 return `<section class="panel engineHome"><span class="eyebrow">ÖLÇÜLEBİLİR KARAR</span><h3>Fırsat, teyit ve risk bir arada</h3>${report?.laterSummary?.count?`<p class="engineEvidence">Son tarih aralığında ${report.laterSummary.count} örnek işlemin net ortalaması %${fmt(report.laterSummary.meanReturn*100,2)}. ${report.laterSummary.meanReturn<=0?'Geçmiş sonuçlar olumsuz; motor deneysel.':'Geriye dönük ölçüm; ileri performans doğrulanmadı.'}</p>`:''}<p>${ready.length} hissede örnek plan koşulları uygun · ${preview.length} olumlu adayda son mum henüz teyitsiz.</p><p>Günlük evre, haftalık teyit, piyasa katılımı ve maliyet sonrası getiri/risk aynı motorla hesaplanır. Her hissenin geçmiş işlem raporu detayında görülebilir.</p>${report?`<small>Geçmiş rapor paketi: ${esc(timeText(report.snapshotAt))}. Bugünkü endeks üyeleriyle geriye dönük ölçüm; ileri performans garantisi değildir.</small>`:''}</section>`;
}
async function refreshEngineReport(){
 if(location.protocol==='file:')return;
 try{const response=await fetch('./analysis-report.json?t='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)return;const report=await response.json();if(report.version===AnalysisEngine.VERSION&&report.assets&&report.generatedAt>=String(window.ANALYSIS_REPORT?.generatedAt||''))window.ANALYSIS_REPORT=report;}catch{/* A mismatched retained report stays hidden by its price fingerprint. */}
}
