const HOME_LISTS={alinabilir:{title:'Olumlu teknik fırsatlar',note:'Trend devamı, kırılım, erken momentum dönüşü ve hacimli toparlanma adayları. Evre ve teyit düzeyi her satırda açıklanır.',label:'ALINABİLİR'},bekleyen:{title:'Teyit bekleyen hisseler',note:'Olumlu ve olumsuz işaretlerin birlikte bulunduğu hisseler. Her satırda hangi teyidin beklendiğini incele.',label:'BEKLE'},sinirli:{title:'Verisi sınırlı varlıklar',note:'Eksik seri, eski kayıt veya kaynak erişim hatası nedeniyle güvenilir karar üretilemeyen varlıklar.',label:'KARAR VERİLEMEZ'},siralama:{title:'Teknik izleme sıralaması',note:'Hisseler 100 üzerinden teknik puana göre sıralanır. Puan başarı ihtimali veya kâr garantisi değildir.'}};
function homeReadings(symbols=ranked()){return symbols.map(sym=>{const x=calc(sym);return {sym,x,verdict:x?decision(x,sym):{label:'KARAR VERİLEMEZ',reasons:['En az 20 günlük kullanılabilir fiyat serisi bulunmuyor.'],change:'Fiyat geçmişinin tamamlanması gerekiyor.'}}})}
function sparkline(x){if(!x)return '';const a=x.a.slice(-30).map(r=>r.c),lo=Math.min(...a),hi=Math.max(...a),span=hi-lo||1,color=a.at(-1)>=a[0]?'#49d7b0':'#ff7188';return `<svg class="homeSpark" viewBox="0 0 160 38" aria-label="Son 30 kayıt kapanış eğilimi"><polyline points="${a.map((v,i)=>`${2+i/(a.length-1||1)*156},${35-(v-lo)/span*32}`).join(' ')}" fill="none" stroke="${color}" stroke-width="2"/></svg>`}
function signalBadge(v){return `<span class="statusPill ${v.label==='ALINABİLİR'?'isBuy':v.label==='ALINMAZ'?'isSell':'isWait'}">${esc(v.setup||v.label)}</span>`}
function homeHealth(){const errors=Object.entries(live.errors||{});return errors.length?`<details class="homeHealth"><summary>${errors.length} varlıkta kaynak erişim sorunu · Ayrıntıları göster</summary>${errors.map(([sym,error])=>`<p><a href="#varlik/${sym}">${esc(CAT[sym]?.[0]||sym)} (${esc(sym)})</a> — ${sym==='ALTINS1'?'Yahoo Finance bu sertifikanın fiyat serisini sağlamıyor (404). Eski kayıtla alım kararı üretilmiyor.':esc(error)}</p>`).join('')}</details>`:'<p class="sourceNote">Son veri paketinde kaynak erişim hatası bildirilmedi.</p>'}
function renderHome(){
 const readings=homeReadings(),buys=readings.filter(i=>i.verdict.label==='ALINABİLİR'),waits=readings.filter(i=>i.verdict.label==='BEKLE'),limited=homeReadings(ALL).filter(i=>i.verdict.label==='KARAR VERİLEMEZ'),leaders=readings.filter(i=>i.x?.fresh).slice(0,6);
 $('homePage').innerHTML=`<section class="appleHero"><span class="eyebrow">PİYASAYA GENEL BAKIŞ</span><h2>Piyasalar.<br><span>Bir bakışta.</span></h2><p>Fiyatlar, sinyaller ve takip ettiklerin.</p><button type="button" id="homeWatchlist" class="primaryLink">Varlıkları keşfet <span aria-hidden="true">↗</span></button></section>
 <div class="marketTiles">${['XAUUSD','GRAMALTIN','BRENT','USDTRY','EURTRY','EURUSD'].map(sym=>{const x=calc(sym),d=latestChange(sym,x);return `<a class="marketTile" href="#varlik/${sym}"><span>${esc(CAT[sym][0])}</span><strong>${x?formatPrice(sym,latestPrice(sym,x)):'—'}</strong><small class="${d>=0?'positive':'negative'}">${x?`${d>=0?'+':''}${fmt(d)}%`:'Veri bekleniyor'}</small>${sparkline(x)}</a>`}).join('')}</div>
 <div class="homeStats actionableStats">${[['alinabilir','Olumlu fırsatlar',buys.length,'positive'],['bekleyen','Teyit bekleyen',waits.length,''],['sinirli','Verisi sınırlı',limited.length,'']].map(([route,label,n,tone])=>`<a href="#liste/${route}"><div><span>${label}</span><strong class="${tone}">${n}</strong></div><span class="appleArrow" aria-hidden="true">↗</span></a>`).join('')}</div>
 <section class="panel appleRanking"><div class="homeSectionHead"><div><span class="eyebrow">İZLEME LİSTESİ</span><h3>Öne çıkan hisseler</h3></div><a href="#liste/siralama">Tümünü gör →</a></div><div class="homeRanking"><table><thead><tr><th>Varlık</th><th>Son fiyat</th><th>Teknik puan</th><th>Sinyal</th></tr></thead><tbody>${leaders.map(({sym,x,verdict})=>`<tr><td><a href="#varlik/${sym}" class="assetOpen">${sym}</a><small>${esc(CAT[sym][0])}</small></td><td>${formatPrice(sym,latestPrice(sym,x))}</td><td>${x.score??'—'}<small>/ 100</small></td><td>${signalBadge(verdict)}</td></tr>`).join('')||'<tr><td colspan="4">Güncel veriler bekleniyor.</td></tr>'}</tbody></table></div></section>
 ${valuationSection()}<details class="panel appleDisclosure"><summary>Veri ve kaynak bilgileri</summary><p class="bodyText">Son çekim: ${esc(timeText(live.generatedAt))}. Fiyatlar gecikmeli; teknik analiz günlük mumlardan hesaplanır.</p>${homeHealth()}</details>`;
 $('homeWatchlist').onclick=()=>{$('watchlistDrawer').showModal();$('openWatchlist').setAttribute('aria-expanded','true');$('search').focus()};
}
function renderHomeList(kind){const config=HOME_LISTS[kind],all=homeReadings(kind==='sinirli'?ALL:ranked()),items=kind==='siralama'?all:all.filter(i=>i.verdict.label===config.label);
 $('homePage').innerHTML=`<section class="listHero"><a href="#anasayfa">← Piyasaya genel bakış</a><h2>${config.title}</h2><p>${config.note}</p><div class="listControls"><span>${items.length} varlık</span><input id="homeListSearch" type="search" placeholder="Kod veya şirket adı ara" aria-label="Bu listede varlık ara"></div></section><div id="homeListResults" class="listResults"></div>`;
 const draw=query=>{$('homeListResults').innerHTML=items.filter(i=>(i.sym+' '+CAT[i.sym][0]).toLocaleLowerCase('tr-TR').includes(query)).map(({sym,x,verdict},i)=>`<article class="listAssetCard"><div class="listAssetTitle"><span class="rankNumber">${i+1}</span><div><a class="assetOpen" href="#varlik/${sym}">${sym} · ${esc(CAT[sym][0])}</a><small>${dateText(entry(sym)?.lastBar)} · ${x?.score===null||!x?.fresh?'Puan geçersiz':x?.score===undefined?'Veri yok':x.score+'/100'}</small></div>${signalBadge(verdict)}</div><div class="listAssetBody"><div><strong>${x?formatPrice(sym,latestPrice(sym,x)):'—'}</strong><p>${esc(verdict.reasons[0])}</p>${live.errors?.[sym]?`<p class="negative">Kaynak hatası: ${sym==='ALTINS1'?'Yahoo Finance bu sertifikayı sağlamıyor (404).':esc(live.errors[sym])}</p>`:''}<small>Kararın değişmesi için: ${esc(verdict.change)}</small></div><a href="#varlik/${sym}" class="primaryLink">Analizi aç →</a></div></article>`).join('')||'<div class="homeEmpty">Bu koşullarda eşleşen varlık bulunamadı.</div>'};
 draw('');$('homeListSearch').addEventListener('input',event=>draw(event.target.value.trim().toLocaleLowerCase('tr-TR')));
}
