const HOME_LISTS={alinabilir:{title:'Alınabilir koşullardaki hisseler',note:'Modelin eğilim, momentum, hacim ve fiyat konumu koşullarını birlikte sağlayan hisseler.',label:'ALINABİLİR'},bekleyen:{title:'Teyit bekleyen hisseler',note:'Olumlu ve olumsuz işaretlerin birlikte bulunduğu hisseler. Her satırda hangi teyidin beklendiğini incele.',label:'BEKLE'},sinirli:{title:'Verisi sınırlı varlıklar',note:'Eksik seri, eski kayıt veya kaynak erişim hatası nedeniyle güvenilir karar üretilemeyen varlıklar.',label:'KARAR VERİLEMEZ'},siralama:{title:'Teknik izleme sıralaması',note:'Hisseler 100 üzerinden teknik puana göre sıralanır. Puan başarı ihtimali veya kâr garantisi değildir.'}};
function homeReadings(symbols=ranked()){return symbols.map(sym=>{const x=calc(sym);return {sym,x,verdict:x?decision(x,sym):{label:'KARAR VERİLEMEZ',reasons:['En az 20 günlük kullanılabilir fiyat serisi bulunmuyor.'],change:'Fiyat geçmişinin tamamlanması gerekiyor.'}}})}
function sparkline(x){if(!x)return '';const a=x.a.slice(-30).map(r=>r.c),lo=Math.min(...a),hi=Math.max(...a),span=hi-lo||1,color=a.at(-1)>=a[0]?'#49d7b0':'#ff7188';return `<svg class="homeSpark" viewBox="0 0 160 38" aria-label="Son 30 kayıt kapanış eğilimi"><polyline points="${a.map((v,i)=>`${2+i/(a.length-1||1)*156},${35-(v-lo)/span*32}`).join(' ')}" fill="none" stroke="${color}" stroke-width="2"/></svg>`}
function signalBadge(v){return `<span class="statusPill ${v.label==='ALINABİLİR'?'isBuy':v.label==='ALINMAZ'?'isSell':'isWait'}">${esc(v.label)}</span>`}
function homeHealth(){const errors=Object.entries(live.errors||{});return errors.length?`<details class="homeHealth"><summary>${errors.length} varlıkta kaynak erişim sorunu · Ayrıntıları göster</summary>${errors.map(([sym,error])=>`<p><a href="#varlik/${sym}">${esc(CAT[sym]?.[0]||sym)} (${esc(sym)})</a> — ${sym==='ALTINS1'?'Yahoo Finance bu sertifikanın fiyat serisini sağlamıyor (404). Eski kayıtla alım kararı üretilmiyor.':esc(error)}</p>`).join('')}</details>`:'<p class="sourceNote">Son veri paketinde kaynak erişim hatası bildirilmedi.</p>'}
function renderHome(){
 const readings=homeReadings(),buys=readings.filter(i=>i.verdict.label==='ALINABİLİR'),waits=readings.filter(i=>i.verdict.label==='BEKLE'),limited=homeReadings(ALL).filter(i=>i.verdict.label==='KARAR VERİLEMEZ');
 const fresh=readings.filter(i=>i.x?.fresh),leaders=fresh.slice(0,8),radar=(buys.length?buys:waits).slice(0,3),moves=[...fresh].sort((a,b)=>latestChange(b.sym,b.x)-latestChange(a.sym,a.x));
 const tiles=['XAUUSD','GRAMALTIN','BRENT','USDTRY','EURTRY','EURUSD'].map(sym=>{const x=calc(sym);return `<a class="marketTile" href="#varlik/${sym}"><span>${esc(CAT[sym][0])}</span><strong>${x?formatPrice(sym,latestPrice(sym,x)):'—'}</strong><small class="${latestChange(sym,x)>=0?'positive':'negative'}">${x?`${latestChange(sym,x)>=0?'+':''}${fmt(latestChange(sym,x))}%`:'Veri yok'} ${x&&!x.fresh?'· veri sınırlı':''}</small>${sparkline(x)}</a>`}).join('');
 const mover=(items,title)=>`<section class="panel moverPanel"><h3>${title}</h3><p class="sourceNote">Son kaydın önceki güne göre değişimi</p>${items.map(({sym,x})=>`<a class="moverRow" href="#varlik/${sym}"><span><b>${sym}</b><small>${esc(CAT[sym][0])}</small></span><span>${formatPrice(sym,latestPrice(sym,x))}<strong class="${latestChange(sym,x)>=0?'positive':'negative'}">${latestChange(sym,x)>=0?'+':''}${fmt(latestChange(sym,x))}%</strong></span></a>`).join('')||'<p class="bodyText">Karşılaştırılabilir güncel veri bulunamadı.</p>'}</section>`;
 $('homePage').innerHTML=`<section class="homeHero premiumHero"><div><span class="eyebrow">ŞANSLI KEDİ · PİYASA RADARI</span><h2>Piyasayı takip et.<br><em>Kararını verilerle destekle.</em></h2><p>Hisselerin teknik görünümü, izlenecek seviyeler ve portföy senaryoları tek yerde. Bir varlığı seçerek analizin dayanaklarını incele.</p><div class="heroActions"><a class="primaryLink" href="#liste/siralama">Hisseleri keşfet →</a><button type="button" class="secondaryLink" id="homeWatchlist">Tüm varlıkları aç</button></div></div><aside class="heroSnapshot"><span>SON PİYASA KAYDI</span><strong>${dateText(live.marketDataAsOf)}</strong><p>${fresh.length}/${STOCKS.length} hisse teknik sıralamaya uygun</p><small>Günlük ve gecikmeli fiyat geçmişi<br>Endeks üyeliği: KAP · Fiyat: Yahoo Finance</small></aside></section>
 <div class="marketTiles">${tiles}</div>${valuationSection()}
 <div class="homeStats actionableStats"><a href="#liste/alinabilir"><span class="statIcon positive">↗</span><div><span>Alınabilir koşullarda</span><strong class="positive">${buys.length}</strong><small>Teknik koşulları sağlayan hisseler</small><b>Listeyi ve nedenlerini gör →</b></div></a><a href="#liste/bekleyen"><span class="statIcon">◷</span><div><span>Teyit bekleyen</span><strong>${waits.length}</strong><small>Ek teyit gerektiren hisseler</small><b>Beklenen koşulları incele →</b></div></a><a href="#liste/sinirli"><span class="statIcon">!</span><div><span>Verisi sınırlı</span><strong>${limited.length}</strong><small>Karar üretilemeyen varlıklar</small><b>Eksikleri ve kaynak hatalarını gör →</b></div></a></div>
 <div class="sectionHeading"><div><span class="eyebrow">TEKNİK KEŞİF</span><h3>Radarında olması gerekenler</h3><p>${buys.length?'Alınabilir koşullardaki ilk hisseler.':'Alım koşulları tam sağlanmadığı için teyit bekleyen hisseler gösteriliyor.'}</p></div><a href="#liste/${buys.length?'alinabilir':'bekleyen'}">Tümünü gör →</a></div>
 <div class="radarGrid">${radar.map(({sym,x,verdict})=>`<article class="radarCard"><div class="candidateTop"><a class="assetOpen" href="#varlik/${sym}">${sym}<small>${esc(CAT[sym][0])}</small></a>${signalBadge(verdict)}</div><div class="radarPrice"><strong>${formatPrice(sym,latestPrice(sym,x))}</strong><span class="${latestChange(sym,x)>=0?'positive':'negative'}">${latestChange(sym,x)>=0?'+':''}${fmt(latestChange(sym,x))}%</span></div>${sparkline(x)}<div class="radarNumbers"><span>Teknik puan<b>${x.score}/100</b></span><span>RSI<b>${fmt(x.rs.at(-1),1)}</b></span><span>Hacim / ort.<b>${x.volratio===null?'—':fmt(x.volratio,2)+'×'}</b></span></div><p>${esc(verdict.reasons[0])}</p><a href="#varlik/${sym}" class="cardAnalysisLink">Analizin tamamını aç →</a></article>`).join('')||'<div class="homeEmpty">Güncel ve yeterli veriyle radar oluşturulamadı. Veri sağlığını incele.</div>'}</div>
 <div class="homeColumns discoveryColumns"><section class="panel"><div class="homeSectionHead"><h3>Teknik izleme sıralaması</h3><a href="#liste/siralama">Tüm hisseler →</a></div><p class="bodyText">Puan, eğilim ve göstergelerin toplamıdır; alım koşulları ayrıca değerlendirilir.</p><div class="homeRanking"><table><thead><tr><th>#</th><th>Varlık</th><th>Puan</th><th>Durum</th></tr></thead><tbody>${leaders.map(({sym,x,verdict},i)=>`<tr><td>${i+1}</td><td><a class="assetOpen" href="#varlik/${sym}">${sym}</a><small>${esc(CAT[sym][0])}</small></td><td>${x.score===null?'—':x.score+'/100'}</td><td>${signalBadge(verdict)}</td></tr>`).join('')||'<tr><td colspan="4">Güncel veri yok.</td></tr>'}</tbody></table></div></section><div class="moverStack">${mover(moves.filter(i=>latestChange(i.sym,i.x)>0).slice(0,3),'Yükseliş öne çıkanlar')}${mover([...moves].reverse().filter(i=>latestChange(i.sym,i.x)<0).slice(0,3),'Düşüş öne çıkanlar')}</div></div>
 <section class="panel"><div class="homeSectionHead"><h3>Veri sağlığı</h3><a href="#liste/sinirli">Sorunlu kayıtları incele →</a></div><p class="bodyText">Kaynak çekimi: ${esc(timeText(live.generatedAt))}. Sayfanın açılma zamanı fiyatın yenilenme zamanı değildir.</p>${homeHealth()}</section>
 <section class="panel"><h3>Bir varlığı incelerken</h3><div class="homeTips"><article><span>01 · EĞİLİM</span><h4>Fiyatı ortalamalarla karşılaştır</h4><p>20 ve 50 günlük ortalamaların konumu eğilimin dayanağını gösterir. Destek altındaki kapanış görünümü değiştirebilir.</p></article><article><span>02 · TEYİT</span><h4>Hacmi ve direnci birlikte oku</h4><p>Direnç aşılırken hacim teyidini kontrol et. Ayrıntılı analizde kararın nedenleri ve değişme koşulları bulunur.</p></article><article><span>03 · SERMAYE</span><h4>İki yönlü senaryo kur</h4><p>Sermaye sekmesinde yükseliş ve düşüşü birlikte hesapla. Hesaplanan kâr hedef veya garanti değildir.</p></article></div></section>`;
 $('homeWatchlist').onclick=()=>{$('watchlistDrawer').showModal();$('openWatchlist').setAttribute('aria-expanded','true');$('search').focus()};
}
function renderHomeList(kind){const config=HOME_LISTS[kind],all=homeReadings(kind==='sinirli'?ALL:ranked()),items=kind==='siralama'?all:all.filter(i=>i.verdict.label===config.label);
 $('homePage').innerHTML=`<section class="listHero"><a href="#anasayfa">← Piyasaya genel bakış</a><h2>${config.title}</h2><p>${config.note}</p><div class="listControls"><span>${items.length} varlık</span><input id="homeListSearch" type="search" placeholder="Kod veya şirket adı ara" aria-label="Bu listede varlık ara"></div></section><div id="homeListResults" class="listResults"></div>`;
 const draw=query=>{$('homeListResults').innerHTML=items.filter(i=>(i.sym+' '+CAT[i.sym][0]).toLocaleLowerCase('tr-TR').includes(query)).map(({sym,x,verdict},i)=>`<article class="listAssetCard"><div class="listAssetTitle"><span class="rankNumber">${i+1}</span><div><a class="assetOpen" href="#varlik/${sym}">${sym} · ${esc(CAT[sym][0])}</a><small>${dateText(entry(sym)?.lastBar)} · ${x?.score===null||!x?.fresh?'Puan geçersiz':x?.score===undefined?'Veri yok':x.score+'/100'}</small></div>${signalBadge(verdict)}</div><div class="listAssetBody"><div><strong>${x?formatPrice(sym,latestPrice(sym,x)):'—'}</strong><p>${esc(verdict.reasons[0])}</p>${live.errors?.[sym]?`<p class="negative">Kaynak hatası: ${sym==='ALTINS1'?'Yahoo Finance bu sertifikayı sağlamıyor (404).':esc(live.errors[sym])}</p>`:''}<small>Kararın değişmesi için: ${esc(verdict.change)}</small></div><a href="#varlik/${sym}" class="primaryLink">Analizi aç →</a></div></article>`).join('')||'<div class="homeEmpty">Bu koşullarda eşleşen varlık bulunamadı.</div>'};
 draw('');$('homeListSearch').addEventListener('input',event=>draw(event.target.value.trim().toLocaleLowerCase('tr-TR')));
}
