const UNIVERSE=window.MARKET_UNIVERSE;
const BIST30=UNIVERSE.groups.XU030,STOCKS=UNIVERSE.groups.XU100;
const EXTRA=['XAUUSD','GRAMALTIN','BRENT','WTI','USDTRY','EURTRY','EURUSD'];
const ALL=[...STOCKS,...EXTRA],CAT=window.MARKET_CATALOG;
let live=window.MARKET_LIVE||{assets:{}},newsData=window.MARKET_NEWS||{assets:{}},calcCache=new Map(),rankingCache=null,chartRange=66,chartInterval='daily',current=routeAsset();
const chartLayers={up:true,down:true,sma20:true,sma50:true,trendSupport:true,trendResistance:true,levelBand:true};
const openGroups=new Set(['BIST 30']);
const $=id=>document.getElementById(id),fmt=(n,d=2)=>Number(n).toLocaleString('tr-TR',{minimumFractionDigits:d,maximumFractionDigits:d}),num=n=>Number.isFinite(n)?fmt(n):'—',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateText=s=>s?new Date(s+'T12:00:00').toLocaleDateString('tr-TR',{day:'numeric',month:'short',year:'numeric'}):'—';
delete live.assets?.ALTINS1;delete live.errors?.ALTINS1;
function entry(sym){return live.assets?.[sym]||null}function rows(sym){let e=entry(sym);return e?.rows?.length?e.rows:window.MARKET_DATA?.[sym]||[]}
function latestPrice(sym,x=calc(sym)){const e=entry(sym);return Number.isFinite(e?.quotePrice)&&e.quotePrice>0&&Number.isFinite(e?.quoteTime)&&e.quoteTime*1000>=Date.parse((e.lastBar||'')+'T00:00:00Z')?e.quotePrice:x?.last.c}
function latestChange(sym,x=calc(sym)){const e=entry(sym);return latestPrice(sym,x)===e?.quotePrice&&Number.isFinite(e?.quoteChangePercent)?e.quoteChangePercent:x?.daily}
function sma(values,n){return AnalysisEngine.sma(values,n)}
function ema(values,n){return AnalysisEngine.ema(values,n)}
function rsi(values,n=14){return AnalysisEngine.rsi(values,n)}
function atr(a){return AnalysisEngine.indicators(a).atr.at(-1)}
function stale(e){if(!e?.lastBar)return true;let days=(Date.now()-new Date(e.lastBar+'T23:59:59Z').getTime())/864e5;return days>4}
let engineMarketCache=null;
function engineMarket(){if(!engineMarketCache)engineMarketCache=AnalysisEngine.buildMarket(live.assets,STOCKS);return engineMarketCache;}
function calc(sym){
 if(calcCache.has(sym))return calcCache.get(sym);const a=rows(sym);if(a.length<20||!validRows(a)){calcCache.set(sym,null);return null;}
 const e=entry(sym),n=a.length,L=a[n-1],prev=a[n-2],I=AnalysisEngine.indicators(a),fresh=!stale(e)&&!live.errors?.[sym]&&e?.source!=='Historical snapshot'&&!(e?.validation?.invalidOHLC>0);
 const result=AnalysisEngine.analyze(a,{entry:e,fresh,isShare:STOCKS.includes(sym),symbol:sym,derived:sym==='GRAMALTIN',marketRecords:engineMarket()});
 const c=I.c,sd=Math.sqrt(c.slice(-20).reduce((sum,v)=>sum+(v-I.m20[n-1])**2,0)/20),ret=k=>n>k?(L.c/c[n-k-1]-1)*100:null;
 const volumes=a.slice(-21,-1).map(r=>r.v),vavg=volumes.length===20&&volumes.every(Number.isFinite)?volumes.reduce((a,b)=>a+b,0)/20:null;
 const x={a,e,last:L,prev,c,m20:I.m20,m50:I.m50,m200:I.m200,rs:I.rsi,mac:I.mac,sig:I.sig,A:I.atr[n-1],volratio:vavg>0&&Number.isFinite(L.v)?L.v/vavg:null,low20:Math.min(...a.slice(-20).map(r=>r.l)),high20:Math.max(...a.slice(-20).map(r=>r.h)),low52:Math.min(...a.slice(-252).map(r=>r.l)),high52:Math.max(...a.slice(-252).map(r=>r.h)),bbUpper:I.m20[n-1]+2*sd,bbLower:I.m20[n-1]-2*sd,ret5:ret(5),ret20:ret(20),ret60:ret(60),daily:(L.c/prev.c-1)*100,score:result.score,parts:result.parts,fresh,engine:result};
 calcCache.set(sym,x);return x;
}
function unit(sym){return ['XAUUSD','BRENT','WTI','EURUSD'].includes(sym)?'USD':['USDTRY','EURTRY','GRAMALTIN','ALTINS1',...BIST30,'ARCLK'].includes(sym)?'TL':'TL'}function formatPrice(sym,n){return n===null||!Number.isFinite(n)?'—':`${fmt(n,unit(sym)==='USD'?2:2)} ${unit(sym)}`}
function ranked(){if(rankingCache)return rankingCache;rankingCache=[...STOCKS].sort((a,b)=>{let A=calc(a),B=calc(b),as=A?.fresh&&A.score!==null?A.score:-1,bs=B?.fresh&&B.score!==null?B.score:-1;return bs-as||a.localeCompare(b)});return rankingCache}
function visibleOrder(){return [...ranked(),...EXTRA]}
function renderList(){
  const q=$('search').value.trim().toLocaleLowerCase('tr-TR'),category=$('category').value;
  const groups=['BIST 30','BIST 100','Altın','Petrol','Döviz'];let count=0;
  $('assetList').innerHTML=groups.map(group=>{
    const symbols=visibleOrder().filter(sym=>CAT[sym][2]===group&&(category==='all'||category===group)&&(!q||(sym+' '+CAT[sym][0]).toLocaleLowerCase('tr-TR').includes(q)));
    if(!symbols.length)return '';count+=symbols.length;
    return `<details class="assetGroup" data-group="${group}" ${q||category!=='all'||openGroups.has(group)?'open':''}><summary>${group==='BIST 100'?'BIST 100 · diğer hisseler':group}<span>${symbols.length}</span></summary><div class="groupAssets">${symbols.map(sym=>{
      const x=calc(sym),stock=STOCKS.includes(sym),verdict=x?decision(x,sym):null,signalClass=!x||!x.fresh?'signalStale':verdict?.label==='ALINABİLİR'?'signalBuy':verdict?.label==='ALINMAZ'?'signalSell':'signalWait',signalLabel=!x?'VERİ YOK':!x.fresh?'VERİ ESKİ':verdict?.label==='ALINABİLİR'?(verdict.setup?.includes('ADAYI')||verdict.setup?.includes('ERKEN')?'ADAY':'OLUMLU'):verdict?.label==='ALINMAZ'?'ZAYIF':verdict?.label==='BEKLE'?'BEKLE':'—',score=stock&&x?.fresh&&x.score!==null?` · ${x.score}/100`:'';
      return `<button class="assetBtn ${signalClass} ${sym===current?'active':''}" data-sym="${sym}" aria-current="${sym===current?'true':'false'}" title="${esc(verdict?.setup||verdict?.label||'Veri yok')}"><span><span class="name">${esc(CAT[sym][0])}</span><span class="code">${sym}${score}${!x?.fresh?' · veri sınırlı':''}</span></span><span class="right"><b>${x?fmt(latestPrice(sym,x)):'—'}</b><small class="sideSignal">${signalLabel}</small><small class="${latestChange(sym,x)>=0?'positive':'negative'}">${x?(latestChange(sym,x)>=0?'+':'')+fmt(latestChange(sym,x))+'%':'Veri yok'}</small></span></button>`;
    }).join('')}</div></details>`;
  }).join('')||'<p class="bodyText">Aramana uygun varlık bulunamadı.</p>';
  $('assetCount').textContent=`${count} / ${ALL.length}`;
  document.querySelectorAll('.assetGroup').forEach(group=>group.addEventListener('toggle',()=>{if(!$('search').value&&$('category').value==='all'){group.open?openGroups.add(group.dataset.group):openGroups.delete(group.dataset.group)}}));
  document.querySelectorAll('.assetBtn').forEach(button=>button.onclick=()=>{navigateAsset(button.dataset.sym);$('watchlistDrawer').close()});
}
function poly(points,color,width=2,dash=''){return `<polyline points="${points}" fill="none" stroke="${color}" stroke-width="${width}" stroke-linejoin="round" stroke-linecap="round" ${dash?`stroke-dasharray="${dash}"`:''}/>`}
function aggregateWeeks(rows){const weeks=[];for(const row of rows){const d=new Date(row.date+'T12:00:00Z'),day=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-day);const key=d.toISOString().slice(0,10);let bar=weeks.at(-1);if(!bar||bar.week!==key){bar={week:key,date:row.date,o:row.o,h:row.h,l:row.l,c:row.c,v:Number.isFinite(row.v)?row.v:null};weeks.push(bar)}else{bar.h=Math.max(bar.h,row.h);bar.l=Math.min(bar.l,row.l);bar.c=row.c;if(Number.isFinite(row.v))bar.v=(bar.v||0)+row.v}}return weeks}
function drawChart(x){
  const all=chartInterval==='weekly'?aggregateWeeks(x.a):x.a,rangeCount=chartInterval==='weekly'?Math.max(1,Math.round(chartRange/5)):chartRange,a=all.slice(-rangeCount),n=a.length,offset=all.length-n,W=1000,H=470,L=58,R=92,T=22,priceBottom=328,volumeTop=365,volumeBottom=433;
  const maPeriod=chartInterval==='weekly'?10:20,maLong=chartInterval==='weekly'?20:50,closes=all.map(r=>r.c),ma20=sma(closes,maPeriod),ma50=sma(closes,maLong);
  const levelWindow=Math.min(chartInterval==='weekly'?10:20,n),support=Math.min(...all.slice(-levelWindow-1,-1).map(r=>r.l)),resistance=Math.max(...all.slice(-levelWindow-1,-1).map(r=>r.h));
  const localExtrema=side=>{const points=[];for(let i=2;i<a.length-2;i++){const value=side==='high'?a[i].h:a[i].l,near=a.slice(i-2,i+3).map(r=>side==='high'?r.h:r.l),extreme=side==='high'?value===Math.max(...near):value===Math.min(...near);if(extreme&&(points.length===0||Math.abs(i-points.at(-1).i)>=2))points.push({i,v:value})}return points};
  const highs=localExtrema('high'),lows=localExtrema('low');
  const trend=(points,direction)=>{if(points.length<2)return null;const second=points.at(-1),first=[...points].reverse().find(p=>p.i<second.i&&Math.abs(p.v-second.v)>Math.max(x.A*.35,second.v*.003));if(!first)return null;const slope=(second.v-first.v)/(second.i-first.i);if(direction==='up'&&slope<=0||direction==='down'&&slope>=0)return null;return {first,second,slope,direction}};
  const risingSupport=trend(lows,'up'),fallingResistance=trend(highs,'down'),risingResistance=trend(highs,'up');
  const rawLow=Math.min(...a.map(r=>r.l)),rawHigh=Math.max(...a.map(r=>r.h)),span=rawHigh-rawLow||rawHigh*.02||1;
  const min=rawLow-span*.12,max=rawHigh+span*.12;
  const Y=v=>T+(max-v)/(max-min)*(priceBottom-T),X=i=>L+(i+.5)*(W-L-R)/n,step=(W-L-R)/n,w=Math.max(2,Math.min(15,step*.62));
  let svg=`<rect x="${L}" y="${T}" width="${W-L-R}" height="${volumeBottom-T}" fill="#1c1c1e" rx="6"/>`;
  for(let j=0;j<6;j++){let value=max-j*(max-min)/5,yy=Y(value);svg+=`<line x1="${L}" x2="${W-R}" y1="${yy}" y2="${yy}" stroke="#343438"/><text x="${W-R+10}" y="${yy+4}" fill="#a1a1a6" font-size="12">${fmt(value)}</text>`}
  const band=Math.max(span*.008,(chartInterval==='weekly'?x.A*Math.sqrt(5):x.A)*.15);
  if(chartLayers.levelBand)for(const [label,value,color] of [['DESTEK',support,'#58d58b'],['DİRENÇ',resistance,'#ff6b76']]){
    const y=Y(value),top=Y(value+band),bottom=Y(value-band);
    svg+=`<rect x="${L}" y="${top}" width="${W-L-R}" height="${Math.max(3,bottom-top)}" fill="${color}" opacity=".1"/><line x1="${L}" x2="${W-R}" y1="${y}" y2="${y}" stroke="${color}" stroke-width="1.5" stroke-dasharray="5 5"/><text x="${L+8}" y="${y-6}" fill="${color}" font-size="11" font-weight="700">${label}</text>`;
  }
  const drawTrend=(trend,label,color)=>{if(!trend)return;const start=Math.max(trend.first.i,n-44),end=n-1,yAt=i=>trend.first.v+trend.slope*(i-trend.first.i),x1=X(start),x2=X(end),y1=Y(yAt(start)),y2=Y(yAt(end));svg+=`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="3" stroke-linecap="round"/><circle cx="${X(trend.first.i)}" cy="${Y(trend.first.v)}" r="5" fill="${color}" stroke="#1c1c1e" stroke-width="2"/><circle cx="${X(trend.second.i)}" cy="${Y(trend.second.v)}" r="5" fill="${color}" stroke="#1c1c1e" stroke-width="2"/><rect x="${Math.max(L+4,Math.min(x2-148,W-R-148))}" y="${Math.max(T+14,Math.min(y2-10,priceBottom-8))}" width="144" height="22" rx="5" fill="#1c1c1e" stroke="${color}"/><text x="${Math.max(L+76,Math.min(x2-76,W-R-76))}" y="${Math.max(T+29,Math.min(y2+5,priceBottom+7))}" text-anchor="middle" fill="${color}" font-size="11" font-weight="700">${label}</text>`};
  if(chartLayers.trendSupport)drawTrend(risingSupport,'YÜKSELEN DESTEK · 2 DİP','#58d58b');if(chartLayers.trendResistance){drawTrend(fallingResistance,'DÜŞEN DİRENÇ · 2 TEPE','#ff6b76');drawTrend(risingResistance,'YÜKSELEN DİRENÇ · 2 TEPE','#e6b75e');}
  const volumes=a.map(r=>r.v).filter(Number.isFinite),vMax=Math.max(1,...volumes)*1.1;
  svg+=`<line x1="${L}" x2="${W-R}" y1="${volumeTop-12}" y2="${volumeTop-12}" stroke="#343438"/><text x="${L+7}" y="${volumeTop+2}" fill="#a1a1a6" font-size="11">HACİM</text>`;
  a.forEach((r,i)=>{let xx=X(i),color=r.c>=r.o?'#58d58b':'#ff6b76',showCandle=r.c>=r.o?chartLayers.up:chartLayers.down,yo=Y(r.o),yc=Y(r.c),vH=Number.isFinite(r.v)?r.v/vMax*(volumeBottom-volumeTop):0;if(showCandle)svg+=`<line x1="${xx}" x2="${xx}" y1="${Y(r.h)}" y2="${Y(r.l)}" stroke="${color}" stroke-width="${Math.min(2,step*.22)}"/><rect x="${xx-w/2}" y="${Math.min(yo,yc)}" width="${w}" height="${Math.max(2,Math.abs(yo-yc))}" fill="${color}" rx="1"/><rect x="${xx-w/2}" y="${volumeBottom-vH}" width="${w}" height="${vH}" fill="${color}" opacity=".52"/>`});
  for(let [series,color,visible] of [[ma20,'#e6b75e',chartLayers.sma20],[ma50,'#69acff',chartLayers.sma50]])if(visible)svg+=poly(a.map((_,i)=>series[i+offset]===null?null:`${X(i)},${Y(series[i+offset])}`).filter(Boolean).join(' '),color,2.3);
  const tickCount=Math.min(6,n),tickIndices=[...new Set(Array.from({length:tickCount},(_,i)=>Math.round(i*(n-1)/Math.max(1,tickCount-1))))];
  tickIndices.forEach(i=>svg+=`<text x="${X(i)}" y="${H-11}" text-anchor="middle" fill="#a1a1a6" font-size="12">${dateText(a[i].date)}</text>`);
  const last=a[n-1],lastColor=last.c>=a[Math.max(0,n-2)].c?'#58d58b':'#ff6b76';
  svg+=`<line x1="${L}" x2="${W-R}" y1="${Y(last.c)}" y2="${Y(last.c)}" stroke="${lastColor}" stroke-width="1.5" stroke-dasharray="3 4" opacity=".85"/><rect x="${W-R+2}" y="${Y(last.c)-11}" width="78" height="22" fill="${lastColor}" rx="4"/><text x="${W-R+41}" y="${Y(last.c)+5}" text-anchor="middle" fill="#101012" font-size="12" font-weight="800">${fmt(last.c)}</text>`;
  svg+=`<g id="chartCursor" visibility="hidden"><line id="chartCursorV" y1="${T}" y2="${volumeBottom}" stroke="#a1a1a6" stroke-width="1" stroke-dasharray="4 4" opacity=".65"/><circle id="chartCursorDot" r="4" fill="#f5f5f7" stroke="#1c1c1e" stroke-width="2"/></g>`;
  a.forEach((r,i)=>svg+=`<rect class="chartHit" data-index="${i}" x="${L+i*step}" y="${T}" width="${step}" height="${volumeBottom-T}" fill="transparent" tabindex="0" aria-label="${r.date}: açılış ${fmt(r.o)}, yüksek ${fmt(r.h)}, düşük ${fmt(r.l)}, kapanış ${fmt(r.c)}"/>`);
  $('priceChart').innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMinYMid meet" aria-hidden="false">${svg}</svg>`;
  const frame=$('chartFrame'),tip=$('chartTooltip'),cursor=$('chartCursor');
  function show(i){let r=a[i],previous=a[i-1],change=previous?(r.c/previous.c-1)*100:0;tip.innerHTML=`<strong>${chartInterval==='weekly'?'Hafta · ':''}${dateText(r.date)}</strong><span>Açılış <b>${fmt(r.o)}</b></span><span>Yüksek <b>${fmt(r.h)}</b></span><span>Düşük <b>${fmt(r.l)}</b></span><span>Kapanış <b>${fmt(r.c)}</b></span><span>Değişim <b class="${change>=0?'positive':'negative'}">${change>=0?'+':''}${fmt(change)}%</b></span><span>Hacim <b>${Number.isFinite(r.v)?fmt(r.v,0):'—'}</b></span>`;tip.hidden=false;let xPos=X(i)/W*$('priceChart').clientWidth;tip.style.left=`${Math.max(6,Math.min(xPos+12,frame.clientWidth-175))}px`;tip.style.top='14px';cursor.setAttribute('visibility','visible');$('chartCursorV').setAttribute('x1',X(i));$('chartCursorV').setAttribute('x2',X(i));$('chartCursorDot').setAttribute('cx',X(i));$('chartCursorDot').setAttribute('cy',Y(r.c))}
  $('priceChart').querySelectorAll('.chartHit').forEach(hit=>{hit.addEventListener('pointerenter',()=>show(Number(hit.dataset.index)));hit.addEventListener('focus',()=>show(Number(hit.dataset.index)))});
  $('priceChart').onpointerleave=()=>{tip.hidden=true;cursor.setAttribute('visibility','hidden')};
  $('priceChart').onfocusout=event=>{if(!event.currentTarget.contains(event.relatedTarget)){tip.hidden=true;cursor.setAttribute('visibility','hidden')}};
  const weeklyRows=chartInterval==='weekly'?aggregateWeeks(x.a):null,weeklyCloses=weeklyRows?.map(r=>r.c)||[],weeklyRSI=weeklyRows?rsi(weeklyCloses):null,rs=chartInterval==='weekly'?weeklyRSI.slice(-chartRange):x.rs.slice(-chartRange),rh=165,ry=v=>18+(100-v)*1.25,rx=i=>L+(i+.5)*(W-L-R)/n;
  let rsvg=`<rect x="${L}" y="${ry(70)}" width="${W-L-R}" height="${ry(30)-ry(70)}" fill="#262629" opacity=".5"/>`;
  for(let k of [30,50,70])rsvg+=`<line x1="${L}" x2="${W-R}" y1="${ry(k)}" y2="${ry(k)}" stroke="#56718d" stroke-dasharray="4 4"/><text x="12" y="${ry(k)+4}" fill="#a1a1a6" font-size="13">${k}</text>`;
  rsvg+=poly(rs.map((v,i)=>v===null?null:`${rx(i)},${ry(v)}`).filter(Boolean).join(' '),'#69acff',3);
  rsvg+=`<text x="${W-R+8}" y="${ry(rs.at(-1))+4}" fill="#69acff" font-size="15" font-weight="700">${Number.isFinite(rs.at(-1))?fmt(rs.at(-1),1):'—'}</text>`;
  $('rsiChart').innerHTML=`<svg viewBox="0 0 ${W} ${rh}" preserveAspectRatio="xMinYMid meet" aria-hidden="true">${rsvg}</svg>`;
  const bars=a.slice(-40),vw=940,vh=145,vl=48,vr=58,base=116,valid=bars.map(r=>r.v).filter(Number.isFinite);
  if(valid.length<10){$('volumeChart').innerHTML='<div class="noVolume">Bu varlık için güvenilir hacim verisi sağlanmıyor.</div>';return}
  const peak=Math.max(...valid)*1.15||1,avg=valid.slice(-20).reduce((sum,v)=>sum+v,0)/Math.min(20,valid.length),vx=i=>vl+(i+.5)*(vw-vl-vr)/bars.length,bw=Math.max(4,(vw-vl-vr)/bars.length*.64),vy=v=>base-v/peak*100;
  let vsvg=`<line x1="${vl}" x2="${vw-vr}" y1="${vy(avg)}" y2="${vy(avg)}" stroke="#e6b75e" stroke-dasharray="5 5" stroke-width="2"/><text x="${vw-vr+5}" y="${vy(avg)+4}" fill="#e6b75e" font-size="11">20G ort.</text>`;
  bars.forEach((r,i)=>{if(!Number.isFinite(r.v))return;let y=vy(r.v);vsvg+=`<rect x="${vx(i)-bw/2}" y="${y}" width="${bw}" height="${base-y}" fill="${r.c>=r.o?'#58d58b':'#ff6b76'}"><title>${r.date}: ${fmt(r.v,0)} hacim</title></rect>`});
  vsvg+=`<text x="${vl}" y="${vh-7}" fill="#a1a1a6" font-size="11">${bars[0].date.slice(5)}</text><text x="${vw-vr}" y="${vh-7}" text-anchor="end" fill="#a1a1a6" font-size="11">${bars.at(-1).date.slice(5)}</text>`;
  $('volumeChart').innerHTML=`<svg viewBox="0 0 ${vw} ${vh}" preserveAspectRatio="xMinYMid meet" aria-hidden="true">${vsvg}</svg>`;
}
function decision(x,sym){
 const result=x.engine;
 return {...result,reasons:[...result.reasons,...result.risks],change:result.change||'Geçerli ve yeterli günlük seri geldiğinde yeniden hesaplanır.',quality:`Motor ${result.version} · ${x.a.length} bar · ${dateText(x.last.date)} · ${result.quality.provisional?'Son mum ön izleme':'Tarihsel / kapanmış günlük veri'}. Puan başarı olasılığı değildir.`};
}
const METRIC_INFO={
 score:{title:'İzleme puanı',tag:'GÖRELİ TEKNİK ÖZET',meaning:'0–100 arası göreli puan; eğilim (25), momentum (20), fiyat yapısı (15), hacim (15), emsale göre güç (15) ve piyasa katılımı (10) toplamıdır.',formula:'En az 60 günlük veri gerekir. Hisse senetlerinde grup içi kıyas içindir; başarı olasılığı değildir.',caution:'Bilanço, değerleme, haberlerin finansal etkisi ve yatırımcının risk profili puana dahil değildir.'},
 rsi:{title:'RSI · 14 günlük momentum',tag:'MOMENTUM',meaning:'Son 14 dönemdeki yukarı ve aşağı kapanış hareketlerini karşılaştıran 0–100 osilatörüdür.',formula:'Genel okuma: 30 altı aşırı satım alanı; 70 üstü aşırı alım alanı. Güçlü trendlerde RSI bu uçlarda uzun süre kalabilir.',caution:'Aşırı satım tek başına al sinyali, aşırı alım da tek başına sat sinyali değildir.'},
 sma20:{title:'20 günlük basit hareketli ortalama',tag:'KISA VADELİ EĞİLİM',meaning:'Son 20 kapanış fiyatının aritmetik ortalamasıdır. Fiyatın üzerindeki/altındaki konumu kısa dönem eğilimi tarif eder.',formula:'SMA20 = son 20 kapanışın toplamı ÷ 20. Gecikmeli bir göstergedir.',caution:'Yatay piyasada sık yön değiştirip yanlış sinyal üretebilir; tek başına destek garantisi değildir.'},
 sma50:{title:'50 günlük basit hareketli ortalama',tag:'ORTA VADELİ EĞİLİM',meaning:'Son 50 kapanışın ortalamasıdır. SMA20 ile birlikte kısa ve orta dönem eğilimini kıyaslamaya yarar.',formula:'Fiyat ve SMA20, SMA50 üstündeyse trend görünümü güçlenebilir; altındaysa zayıflayabilir.',caution:'Trendin gerisinden gelir ve gelecekteki fiyatı tahmin etmez. 50 günden kısa seride güvenilir hesaplanamaz.'},
 macd:{title:'MACD · 12/26/9',tag:'TREND VE MOMENTUM',meaning:'12 dönemlik üssel ortalamadan 26 dönemlik üssel ortalamanın çıkarılmasıyla elde edilir. Sinyal çizgisi MACD’nin 9 dönemlik ortalamasıdır.',formula:'MACD sinyal çizgisinin üzerindeyse momentum olumlu; altındaysa zayıf yönde okunur. Sıfır çizgisi trend bağlamı sağlar.',caution:'Keskin veya yatay hareketlerde gecikme ve yalancı kesişim olabilir. Değer, hisse fiyatı ölçeğinden etkilenir.'},
 atr:{title:'ATR · 14 günlük oynaklık',tag:'RİSK VE FİYAT ARALIĞI',meaning:'Gerçek fiyat aralıklarının Wilder 14 dönem yumuşatmasını ölçer; yön göstermez.',formula:'ATR / son fiyat yüzdesi günlük tipik hareket genişliğine dair ölçek verir. Stop mesafesi için tek başına yeterli değildir.',caution:'Yüksek ATR daha geniş fiyat salınımı demektir; yükseliş anlamına gelmez. Haber günlerinde hızla değişebilir.'}
};
function metricTone(key,x){if(key==='fair'){const v=fairValue(current);return v&&x?.fresh?(v.value>x.last.c?'positive':'negative'):'neutral'}if(!x)return 'neutral';let i=x.a.length,k=x.last.c;if(key==='score')return x.score>=65?'positive':x.score<45?'negative':'neutral';if(key==='rsi'){let v=x.rs[i-1];return v>=45&&x.last.c>x.m20[i-1]?'positive':v<30?'negative':'neutral'}if(key==='sma20'||key==='sma50'){let ma=key==='sma20'?x.m20[i-1]:x.m50[i-1];return !Number.isFinite(ma)?'neutral':k>ma?'positive':k<ma?'negative':'neutral'}if(key==='macd')return x.mac[i-1]>x.sig[i-1]?'positive':'negative';if(key==='atr')return x.A/k>=.06?'negative':x.A/k<=.03?'positive':'neutral';return 'neutral'}
function openMetric(key){if(key==='fair'){openFairValue();return}const info=METRIC_INFO[key],x=calc(current);if(!info||!x)return;const n=x.a.length,L=x.last.c,percent=v=>`${v>=0?'+':''}${fmt(v,2)}%`,rows={score:[['Güncel değer',x.score===null?'—':`${x.score}/100`],['Alt puanlar',x.parts?Object.entries(x.parts).map(([k,v])=>`${k}: ${v}`).join(' · '):'Yetersiz veri'],['Okuma',x.score>=65?'Teknik bileşenler görece güçlü':x.score<45?'Teknik bileşenler zayıf':'Karışık / orta görünüm']],rsi:[['Güncel RSI',num(x.rs[n-1],1)],['5 günlük fiyat değişimi',percent(x.ret5)],['Okuma',x.rs[n-1]<30?'Aşırı satım alanı':x.rs[n-1]>70?'Aşırı alım alanı':x.rs[n-1]>=45&&x.rs[n-1]<=65?'Orta bant':'Nötr / zayıf bant']],sma20:[['SMA20',formatPrice(current,x.m20[n-1])],['Son fiyat',formatPrice(current,L)],['Fiyatın ortalamaya farkı',percent((L/x.m20[n-1]-1)*100)],['Konum',L>x.m20[n-1]?'Ortalamanın üzerinde':'Ortalamanın altında']],sma50:[['SMA50',formatPrice(current,x.m50[n-1])],['Son fiyat',formatPrice(current,L)],['Fiyatın ortalamaya farkı',percent((L/x.m50[n-1]-1)*100)],['Konum',L>x.m50[n-1]?'Ortalamanın üzerinde':'Ortalamanın altında']],macd:[['MACD',num(x.mac[n-1],4)],['Sinyal çizgisi',num(x.sig[n-1],4)],['Önceki MACD',num(x.mac[n-2],4)],['Kesin yön okuması',x.mac[n-1]>x.sig[n-1]?'MACD sinyalin üzerinde':'MACD sinyalin altında']],atr:[['ATR(14)',formatPrice(current,x.A)],['ATR / fiyat',`%${fmt(x.A/L*100,2)}`],['20 günlük aralık',`%${fmt(x.ret20,2)}`],['20 günlük destek / direnç',`${formatPrice(current,x.low20)} / ${formatPrice(current,x.high20)}`]]}[key];const tone=metricTone(key,x);$('metricDialogTag').textContent=info.tag;$('metricDialogTitle').textContent=CAT[current][0]+' · '+info.title;$('metricDialogBody').innerHTML=`<div class="metricDialogStatus ${tone}">${tone==='positive'?'Olumlu teknik görünüm':tone==='negative'?'Olumsuz / dikkat gerektiren görünüm':'Nötr veya karışık görünüm'} <span>Son bar: ${dateText(x.last.date)} · ${n} kayıt</span></div><p>${esc(info.meaning)}</p><div class="metricDialogGrid">${rows.map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('')}</div><h3>Nasıl hesaplanır?</h3><p>${esc(info.formula)}</p><h3>Bu gösterge neyi söylemez?</h3><p>${esc(info.caution)}</p>`;$('metricDialog').showModal()}
function drawGauge(id,value,label,kind,detail){const host=$(id);if(!host)return;const score=Math.max(0,Math.min(100,Number(value)||0)),cx=180,cy=142,r=105,colors=['#d34250','#f18539','#a8b0bb','#3884e7','#079982'];let arcs='';for(let i=0;i<5;i++){const a1=Math.PI+Math.PI*i/5+.045,a2=Math.PI+Math.PI*(i+1)/5-.045,x1=cx+r*Math.cos(a1),y1=cy+r*Math.sin(a1),x2=cx+r*Math.cos(a2),y2=cy+r*Math.sin(a2);arcs+=`<path d="M ${x1} ${y1} A ${r} ${r} 0 0 1 ${x2} ${y2}" fill="none" stroke="${colors[i]}" stroke-width="14" stroke-linecap="round"/>`}const angle=Math.PI+Math.PI*score/100,tx=cx+74*Math.cos(angle),ty=cy+74*Math.sin(angle),tone=score<35?'#ff6b76':score<60?'#a1a1a6':'#58d58b';host.innerHTML=`<div class="gaugeDial"><svg viewBox="0 0 360 168" role="img" aria-label="${esc(label)} · ${Math.round(score)} puan"><title>${esc(label)} · ${Math.round(score)} puan</title>${arcs}<line x1="${cx}" y1="${cy}" x2="${tx}" y2="${ty}" stroke="#f5f5f7" stroke-width="4" stroke-linecap="round"/><circle cx="${cx}" cy="${cy}" r="7" fill="#f5f5f7"/><text x="${cx}" y="151" class="gaugeValue" fill="${tone}">${Math.round(score)}</text></svg></div><div class="gaugeReadout"><strong style="--gauge-tone:${tone}">${esc(label)}</strong><div class="gaugeScaleWrap"><span>Sınırlı</span><span>Nötr</span><span>Güçlü</span></div><div class="gaugeDetail">${esc(detail)}</div></div>`}
function renderGauges(x,sym){if(!x)return;const e=x.engine;drawGauge('technicalGauge',e.score??0,e.score===null?'Veri yetersiz':'Kanıt puanı','technical','Açıklanabilir bileşenler · başarı olasılığı değil');drawGauge('ratingGauge',e.score??0,e.setup,'rating',e.action);}

function set(id,value){$(id).textContent=value}function metric(id,value,note){set(id,value);set(id+'Text',note)}
function renderDetail(){restorePositionInputs(current);let m=CAT[current],x=calc(current),e=entry(current);if(!x){$('detail').hidden=true;$('emptyState').hidden=false;set('emptyState',`${m[0]} için doğrulanmış en az 20 günlük fiyat geçmişi yok. Veri kaynağı yenilendiğinde analiz otomatik açılacak.`);return}$('detail').hidden=false;$('emptyState').hidden=true;let n=x.a.length,L=x.last,fmtp=v=>formatPrice(current,v),lastDate=e?.lastBar||L.date,staleData=!x.fresh;set('assetSector',`${m[1]} · ${m[2]}`);set('assetName',m[0]);set('assetTicker',current==='ALTINS1'?'ALTIN.S1':current);const hasQuote=Number.isFinite(e?.quotePrice)&&Number.isFinite(e?.quoteTime)&&e.quoteTime*1000>=new Date(lastDate+'T00:00:00Z').getTime();set('lastPrice',fmtp(hasQuote?e.quotePrice:L.c));set('dailyChange',`${x.daily>=0?'+':''}${fmt(x.daily)}% · önceki ${fmtp(x.prev.c)}`);$('dailyChange').className='change '+(x.daily>=0?'positive':'negative');set('quoteDate',hasQuote?`Son fiyat zamanı: ${timeText(new Date(e.quoteTime*1000).toISOString())} · ${STOCKS.includes(current)?'15 dk gecikmeli':'kaynak fiyatı'} · analiz: günlük mumlar`:`${dateText(lastDate)} · günlük mum fiyatı · ${e?.source||'tarihsel kayıt'}`);if(hasQuote)set('dailyChange',Number.isFinite(e.quoteChangePercent)?`${e.quoteChangePercent>=0?'+':''}${fmt(e.quoteChangePercent)}% · kaynağın son fiyatı`:'Kaynağın son fiyatı · değişim bilgisi yok');let banner=staleData?`Bu varlıkta son kayıt ${dateText(lastDate)}. Kaynak hatası, fiyat tutarlılığı sorunu veya eski veri var; puan ve alım sırası geçerli sayılmaz.`:`Son kayıt ${dateText(lastDate)}. Günlük veri gecikmeli olabilir; seans içindeki son bar kapanmamış olabilir.`;banner+=` Teknik hesapların son mumu: ${dateText(lastDate)}; ${e?.validation?.quoteCompletedBars?'son mumun eksik kapanışı aynı günün kaynak son fiyatıyla tamamlandı.':'son fiyat kaynak bilgisiyle gösterilir.'}`;set('dataBanner',banner);$('dataBanner').className='dataBanner '+(staleData?'stale':'');metric('score',x.score===null?'—':`${x.score}/100`,x.score===null?'En az 60 gün gerekli':staleData?'Veri sınırlı; sıralama dışı':'Göreli teknik izleme sırası');metric('rsi',num(x.rs[n-1],1),x.rs[n-1]<30?'Aşırı satım':x.rs[n-1]>70?'Aşırı alım':'Momentum göstergesi');metric('sma20',fmtp(x.m20[n-1]),L.c>x.m20[n-1]?'Fiyat üzerinde':'Fiyat altında');metric('sma50',fmtp(x.m50[n-1]),x.m50[n-1]===null?'Veri yetersiz':L.c>x.m50[n-1]?'Fiyat üzerinde':'Fiyat altında');metric('macd',num(x.mac[n-1],3),`Sinyal ${num(x.sig[n-1],3)}`);metric('atr',fmtp(x.A),`Fiyatın %${fmt(x.A/L.c*100,1)} kadarı`);renderFairValue();document.querySelectorAll('.metric[data-metric]').forEach(card=>{const tone=metricTone(card.dataset.metric,x);card.classList.toggle('metric-positive',tone==='positive');card.classList.toggle('metric-negative',tone==='negative');card.classList.toggle('metric-neutral',tone==='neutral')});renderGauges(x,current);drawChart(x);updateChartNote(x);
let verdict=decision(x,current);$('signal').textContent=verdict.setup||verdict.label;$('signal').className='signal '+verdict.style;set('signalText',verdict.action+' · '+(verdict.quality.provisional?'':'')+'Vade: günlük sinyal, en fazla 10 işlem günü için örnek plan.');$('decisionReasons').innerHTML=verdict.reasons.map(reason=>`<li>${esc(reason)}</li>`).join('');set('decisionChange',verdict.change);set('qualityNote',verdict.quality);$('scoreBreakdown').innerHTML=x.parts?Object.entries(x.parts).map(([k,v])=>`<div>${esc(k)}<b>${v}</b></div>`).join(''):'<div>60 günlük seri gerekiyor</div>';let levelUnit=unit(current);$('levels').innerHTML=[['Önceki 20G destek',Math.min(...x.a.slice(-21,-1).map(r=>r.l))],['Önceki 20G direnç',Math.max(...x.a.slice(-21,-1).map(r=>r.h))],['Bollinger alt',x.bbLower]].map(([name,v])=>`<div class="level"><span>${name}</span><b>${fmt(v)} ${levelUnit}</b></div>`).join('');set('volumeText',x.volratio===null?'Bu varlıkta karşılaştırılabilir işlem hacmi sağlanmıyor.':'Son hacim, son mum hariç önceki 20 günlük ortalamanın '+fmt(x.volratio,2)+' katı. Yüksek hacim fiyat hareketinin büyüklüğünü destekleyebilir; yönünü tek başına doğrulamaz.');$('returns').innerHTML=[['5 gün',x.ret5],['20 gün',x.ret20],['60 gün',x.ret60]].map(([label,v])=>`<div>${label}<b class="${v>=0?'positive':'negative'}">${v===null?'—':(v>=0?'+':'')+fmt(v)+'%'}</b></div>`).join('');$('technicalTable').innerHTML=[['SMA20',x.m20[n-1]],['SMA50',x.m50[n-1]],['SMA200',x.m200[n-1]],['Bollinger üst',x.bbUpper],['Bollinger alt',x.bbLower],['20G en düşük',x.low20],['20G en yüksek',x.high20],['1Y en düşük',x.low52],['1Y en yüksek',x.high52],['MACD sinyal',x.sig[n-1]],['Hacim / ort.',x.volratio],['ATR / fiyat %',x.A/L.c*100]].map(([label,v])=>`<div><span>${label}</span><b>${v===null?'—':fmt(v,label.includes('%')||label.includes('Hacim')?2:3)}</b></div>`).join('');set('bullText',m[3]);set('bearText',m[4]);set('evidenceText',m[5]);let sources=[[`Fiyat kaynağı: ${e?.source||'tarihsel snapshot'}`,e?.sourceUrl||'https://finance.yahoo.com/'],['KAP şirket bilgileri ve bildirimleri',kapUrl(current)]];if(BIST30.includes(current))sources.push(['KAP güncel endeks üyeliği','https://kap.org.tr/tr/Endeksler']);if(current==='ALTINS1')sources.push(['Borsa İstanbul sertifika ürün tanımı','https://www.borsaistanbul.com/en/participation-finance/turkish-state-mint-gold-certificate']);if(['USDTRY','EURTRY','EURUSD'].includes(current))sources.push(['TCMB gösterge kurları','https://www.tcmb.gov.tr/']);$('sourceList').innerHTML=sources.map(([label,url])=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`).join('');set('dataLimit',`${n} günlük veri; son piyasa tarihi ${dateText(lastDate)}. Dosya indirme zamanı ${e?.fetchedAt?new Date(e.fetchedAt).toLocaleString('tr-TR'):'bilinmiyor'}.`);renderHistory(x);renderPlan(x);renderEnginePanel(x)}
function renderHistory(x){$('historyTable').innerHTML=`<table><thead><tr><th>Tarih</th><th>Açılış</th><th>Yüksek</th><th>Düşük</th><th>Kapanış</th><th>Hacim</th></tr></thead><tbody>${[...x.a].reverse().slice(0,90).map(r=>`<tr><td>${dateText(r.date)}</td><td>${fmt(r.o)}</td><td>${fmt(r.h)}</td><td>${fmt(r.l)}</td><td>${fmt(r.c)}</td><td>${Number.isFinite(r.v)?fmt(r.v,0):'—'}</td></tr>`).join('')}</tbody></table>`}
function renderPlan(x=calc(current)){
 if(!x)return;const cap=Math.max(0,Number($('capital').value)||0),up=Math.max(0,Number($('upPct').value)||0),down=Math.max(0,Number($('downPct').value)||0),usd=unit(current)==='USD',fx=calc('USDTRY'),rate=usd?(fx?.fresh?fx.last.c:null):1,stock=STOCKS.includes(current),price=latestPrice(current,x)*rate;
 if(!Number.isFinite(rate)||!(price>0)){for(const id of ['maxQty','spend','profit','upValue','loss','downValue','riskQty','riskInfo'])set(id,'Güncel dönüşüm kuru yok');return;}
 const qty=stock?Math.floor(cap/price):cap/price,spent=qty*price,profit=spent*up/100,loss=spent*down/100;
 set('maxQty',`${fmt(qty,stock?0:2)} ${stock?'adet':'birim'}`);set('spend',`${fmt(spent)} TL kullanılır · ${fmt(cap-spent)} TL kalır`);set('profit','+'+fmt(profit)+' TL');set('upValue',`Fiyat +%${fmt(up)} olursa toplam ${fmt(cap+profit)} TL`);set('loss','−'+fmt(loss)+' TL');set('downValue',`Fiyat −%${fmt(down)} olursa toplam ${fmt(cap-loss)} TL`);
 const p=x.engine.plan,sized=stock&&x.engine.tradable?AnalysisEngine.sizePosition(p,cap,Number($('riskPct').value),Number($('allocationPct').value),rate):{quantity:0,estimatedRisk:0};set('riskQty',`${sized.quantity} adet`);set('riskInfo',p?`Örnek stop ${formatPrice(current,p.stop)} · maliyet dahil risk ${fmt(sized.estimatedRisk)} TL`:'Geçerli giriş planı yok');
}

function safeUrl(value){try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)?url.href:'#'}catch{return '#'}}
function kapUrl(sym){const id=UNIVERSE.companies[sym]?.kapId;return id?'https://kap.org.tr/tr/sirket-bilgileri/ozet/'+encodeURIComponent(id):'https://kap.org.tr/tr/'}
function validRows(rows){return rows.every((r,i)=>/^\d{4}-\d{2}-\d{2}$/.test(r.date)&&(!i||rows[i-1].date<r.date)&&['o','h','l','c'].every(key=>Number.isFinite(r[key])&&r[key]>0)&&r.l<=Math.min(r.o,r.c)&&r.h>=Math.max(r.o,r.c)&&(r.v===null||r.v===undefined||Number.isFinite(r.v)&&r.v>=0))}
function timeText(value){return value&&!Number.isNaN(new Date(value).getTime())?new Date(value).toLocaleString('tr-TR'):'belirtilmemiş'}
function renderNews(){
  const record=newsData.assets?.[current],items=Array.isArray(record?.items)?record.items:[],decisions=Array.isArray(newsData.disclosures?.[current])?newsData.disclosures[current]:[];
  set('newsTitle',CAT[current][0]+' · haber akışı ve şirket kararları');
  const kapError=newsData.disclosureErrors?.[current];
  set('newsStatus',`${decisions.length} KAP tam metin kontrolü · ${items.length} medya başlığı · veri paketi ${timeText(newsData.generatedAt)}${kapError?' · KAP erişim sorunu, kayıtlı sonuç korunuyor':''}`);
  $('kapNewsList').innerHTML=decisions.length?decisions.map(item=>`<article class="newsCard kapCard"><div class="newsMeta"><span>✓ KAP tam metni açıldı · ${esc(item.decisionType)}</span><time datetime="${esc(item.publishedAt)}">${esc(timeText(item.publishedAt))}</time></div><a class="newsTitle" href="${esc(safeUrl(item.url))}" target="_blank" rel="noopener noreferrer">${esc(item.title)} ↗</a><div class="newsInterpretation"><b>Şirketin açıklaması</b><p>${esc(item.summary)}</p></div><div class="newsInterpretation"><b>Olası finansal kanal · ${esc(item.directionalReading)}</b><p>${esc(item.potentialChannel)}</p>${item.amounts?.length?`<p><b>Metinde geçen tutar:</b> ${esc(item.amounts.join(' · '))}. Açıklanan tutar otomatik olarak kâr/zarar kabul edilmez.</p>`:''}</div><div class="newsMeta"><span>Bu karar tek başına fiyat etkisini veya gerçekleşmiş kârı kanıtlamaz.</span><a href="${esc(safeUrl(item.url))}" target="_blank" rel="noopener noreferrer">KAP bildirimini aç ↗</a></div></article>`).join(''):`<div class="newsEmpty">${kapError?'KAP bildirimleri şu an alınamadı. Önceki doğrulanmış kayıt yok.':'Son 31 günde seçilen şirket adına eşleştirilmiş KAP bildirimi yok. Bu, şirketin KAP’ta hiç bildirimi olmadığı anlamına gelmez.'}</div>`;
  $('newsList').innerHTML=items.length?items.map(item=>`<article class="newsCard"><div class="newsMeta"><span>${esc(item.publisher)} · başlık eşleşmesi</span><time datetime="${esc(item.publishedAt)}">${esc(timeText(item.publishedAt))}</time></div><a class="newsTitle" href="${esc(safeUrl(item.url))}" target="_blank" rel="noopener noreferrer">${esc(item.title)} ↗</a><div class="newsInterpretation"><b>Ön okuma</b><p>Yayıncı makalesinin tam metni bu akıştan doğrulanmadı. Bu nedenle başlık, şirketin kesinleşmiş kararı veya doğrulanmış finansal etki olarak yorumlanmıyor.</p></div><div class="newsMeta"><span>Eşleşen ifade: ${esc(item.matchedTerm)}</span><a href="${esc(safeUrl(item.publisherUrl))}" target="_blank" rel="noopener noreferrer">Yayıncı sitesi</a></div></article>`).join(''):`<div class="newsEmpty">${record?.error?'Medya haber kaynağına ulaşılamadı.':'Son 30 günlük başlık taramasında eşleşme yok. Bu, haber olmadığı anlamına gelmez.'}</div>`;
}
function renderSources(){
  const e=entry(current),x=calc(current),record=newsData.assets?.[current],n=e?.rows?.length||0,validation=e?.validation;
  const publishers=[...new Set((record?.items||[]).map(item=>item.publisher))],verified=(newsData.disclosures?.[current]||[]).length;
  $('analysisSources').innerHTML=`<div class="sourceAudit"><span>Teknik analizin girdisi</span><p>${n} günlük açılış, yüksek, düşük, kapanış${STOCKS.includes(current)?' ve işlem hacmi':''}. RSI, SMA, MACD, ATR ve puan bu seri üzerinden hesaplanır.</p><a href="${esc(safeUrl(e?.sourceUrl))}" target="_blank" rel="noopener noreferrer">${esc(e?.source||'Fiyat kaynağı yok')} ↗</a></div><div class="sourceAudit"><span>Veri kontrolü</span><p>${n?dateText(e.rows[0].date)+' – '+dateText(e.lastBar):'Seri yok'} · ${x?'Fiyat sırası ve OHLC tutarlılığı kontrol edildi.':'Geçerli analiz serisi bulunamadı.'} ${validation?`${validation.receivedBars} gelen satır, ${validation.acceptedBars} kullanılan satır, ${validation.missingOHLC??0} boş fiyat satırı, ${validation.invalidOHLC??0} tutarsız fiyat satırı.`:'Kaynak satır kontrolü raporu yok.'}</p><small>Kaynak kontrolü: ${esc(timeText(e?.checkedAt||e?.fetchedAt))}. ${live.errors?.[current]?'Son alım başarısız. ':''}Tek kaynaktan alınan fiyatlar ikinci bir sağlayıcıyla karşılaştırılmadı.</small></div><div class="sourceAudit"><span>Haber ve karar kaynakları</span><p>KAP tam metin kontrolü: ${verified} bildirim. ${publishers.length?esc(publishers.join(' · ')):'Eşleşen medya yayıncısı yok.'}</p><small>${record?.items?.length||0} medya başlığı; kontrol ${esc(timeText(record?.checkedAt))}. Medya tam metni doğrulanmış sayılmaz. KAP sınıflandırması kural tabanlı ön okumadır, otomatik al/sat tetiklemez.</div><div class="sourceAudit"><span>Temel analiz kapsamı</span><p>Sektör çarpanları ayrı kaynaktan alınır; teknik puana karıştırılmaz. Borç ve nakit akışı için tam şirket modeli kurulmaz. Resmî kayıtlar ek kontrol kaynağıdır.</p><a href="${esc(kapUrl(current))}" target="_blank" rel="noopener noreferrer">${STOCKS.includes(current)?'Şirketin KAP sayfası':'KAP'} ↗</a>${STOCKS.includes(current)?` · <a href="${esc(UNIVERSE.sourceUrl)}" target="_blank" rel="noopener noreferrer">Endeks üyeliği</a>`:''}</div>`;
}
async function refreshNews(){
  if(location.protocol==='file:')return;
  try{const response=await fetch('./market-news.json?t='+Date.now(),{cache:'no-store'});if(!response.ok)throw Error('HTTP '+response.status);const latest=await response.json();if(!latest.assets)throw Error('Geçersiz haber verisi');if(latest.generatedAt>=String(newsData.generatedAt||'')){newsData=latest;if(current){renderNews();renderSources()}}}
  catch{set('newsStatus','Haber dosyası yenilenemedi; kayıtlı haberlerin tarihlerini kontrol edin.')}
}

function updateChartNote(x){const count=chartInterval==='weekly'?aggregateWeeks(x?.a||[]).length:(x?.a.length||0),shown=Math.min(chartRange,count),last=chartInterval==='weekly'?aggregateWeeks(x?.a||[]).at(-1)?.date:x?.last.date;set('chartNote',`${chartInterval==='weekly'?'Haftalık':'Günlük'} görünüm · ${shown} mum · son bar ${dateText(last)}. Haftalık OHLC ve hacim günlük barlardan birleştirilir; haftanın son günü henüz tamamlanmamış olabilir. Yatay destek/direnç son mum hariç önceki ${chartInterval==='weekly'?'10 hafta':'20 gün'} içinden, eğik çizgiler iki belirgin tepe/dip temasından hesaplanır.`)}
function renderStatus(mode='snapshot',checkedAt=null){
 const generated=live.generatedAt?new Date(live.generatedAt).toLocaleString('tr-TR'):'—',errors=Object.entries(live.errors||{});
 const label=mode==='fetching'?`Kaynak verisi çekiliyor · ${sourceRefreshProgress}`:mode==='source'?sourceRefreshSummary:mode==='error'?(sourceRefreshSummary||'Veri alınamadı; önceki kayıt korunuyor.'):mode==='live'?'Yayımlanan paket okundu':mode==='local'?'Yerel kayıtlı paket':'Kayıtlı veri paketi';
 $('refreshStatus').innerHTML=`<strong class="demoTitle">Piyasa verileri</strong><span class="lamp"></span> ${esc(label)}<details class="statusDisclosure"><summary>Veri ayrıntıları</summary><small>Veri çekimi: ${esc(generated)} · son günlük mum: ${dateText(live.marketDataAsOf)}${current&&entry(current)?.quoteTime?` · fiyat zamanı: ${esc(timeText(new Date(entry(current).quoteTime*1000).toISOString()))}`:''}. BIST fiyatları 15 dk gecikmeli; seans kapalıyken son işlem fiyatı korunur.</small></details><button id="refreshSource" class="smallBtn" type="button" ${sourceRefreshBusy?'disabled':''}>${sourceRefreshBusy?'Çekiliyor…':current?'Bu varlığı kaynaktan yenile':'Tüm verileri kaynaktan yenile'}</button>${errors.length?`<details class="sourceErrors"><summary>${errors.length} varlıkta veri kaynağı sorunu</summary>${errors.map(([sym,error])=>`<p><a href="#varlik/${sym}">${esc(sym)}</a>: ${sym==='ALTINS1'?'Sertifika bu sağlayıcıda yok (404); eski kayıt kullanılabilir, karar üretilmez.':esc(error)}</p>`).join('')}</details>`:''}`;
}
function routeAsset(){const match=location.hash.match(/^#varlik\/([A-Z0-9]+)$/);return match&&ALL.includes(match[1])?match[1]:null}
function navigateAsset(sym){if(!ALL.includes(sym))return;location.hash='varlik/'+sym}
function renderContent(){
  renderList();$('homePage').hidden=!!current;
  set('routeLabel',current?`${current} · ${CAT[current][0]}`:'Piyasaya genel bakış');
  if(current){renderDetail();renderNews();renderSources()}else{$('detail').hidden=true;$('emptyState').hidden=true;const list=location.hash.match(/^#liste\/(alinabilir|bekleyen|sinirli|siralama)$/);if(list){renderHomeList(list[1]);set('routeLabel',HOME_LISTS[list[1]].title)}else renderHome()}
}
function render(){renderStatus();renderContent()}
window.addEventListener('hashchange',()=>{current=routeAsset();render();window.scrollTo({top:0,behavior:'instant'});if(current)$('assetName').focus({preventScroll:true});if(location.protocol==='https:'&&marketApiBase())refreshFromSource()});
async function refresh(){await refreshMembership();refreshNews();if(location.protocol==='file:'){renderStatus('local');return}try{let response=await fetch(`./market-live.json?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw Error(`HTTP ${response.status}`);let latest=await response.json();if(!latest?.assets)throw Error('Geçersiz veri dosyası');if(latest.generatedAt>=String(live.generatedAt||'')){live=latest;pruneInactiveAssets();calcCache.clear();engineMarketCache=null;rankingCache=null}await refreshEngineReport();renderStatus('live',Date.now());renderContent();if(location.protocol==='https:'&&marketApiBase())await refreshFromSource()}catch(error){renderStatus('error');$('refreshStatus').insertAdjacentHTML('beforeend',`<small>${esc(error.message||'Bağlantı hatası')} · yeni veri için GitHub Actions çalıştırmasını kontrol edin.</small>`)}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabPage').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});for(let id of ['search','category'])$(id).addEventListener('input',renderList);for(let id of ['capital','upPct','downPct','riskPct','allocationPct','heldQty','heldCost'])$(id).addEventListener('input',()=>{rememberPositionInputs();renderPlan();renderEnginePanel(calc(current));});render();refresh();document.addEventListener('click',event=>{if(event.target.closest('#refreshSource'))refreshFromSource()});document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});setInterval(()=>{if(!document.hidden&&location.protocol!=='file:')refresh()},300000);

document.querySelectorAll('.legendToggle input[data-layer]').forEach(input=>input.addEventListener('change',()=>{chartLayers[input.dataset.layer]=input.checked;const x=calc(current);if(x)drawChart(x)}));
document.querySelectorAll('.rangeBtn').forEach(button=>button.addEventListener('click',()=>{chartRange=Number(button.dataset.range);document.querySelectorAll('.rangeBtn').forEach(item=>item.classList.toggle('active',item===button));let x=calc(current);if(x)drawChart(x);updateChartNote(x)}));
document.querySelectorAll('.intervalBtn').forEach(button=>button.addEventListener('click',()=>{chartInterval=button.dataset.interval;document.querySelectorAll('.intervalBtn').forEach(item=>item.classList.toggle('active',item===button));$('priceChartTitle').textContent=chartInterval==='weekly'?'Haftalık fiyat grafiği':'Günlük fiyat grafiği';$('priceChart').setAttribute('aria-label',`Etkileşimli ${chartInterval==='weekly'?'haftalık':'günlük'} fiyat ve hacim grafiği`);let x=calc(current);if(x)drawChart(x);updateChartNote(x)}));

document.querySelectorAll('.metric[data-metric]').forEach(card=>card.addEventListener('click',()=>openMetric(card.dataset.metric)));$('closeMetricDialog').onclick=()=>$('metricDialog').close();$('metricDialog').addEventListener('click',event=>{if(event.target===$('metricDialog'))$('metricDialog').close()});
const drawer=$('watchlistDrawer');
$('openWatchlist').onclick=()=>{drawer.showModal();$('openWatchlist').setAttribute('aria-expanded','true');$('search').focus()};
$('closeWatchlist').onclick=()=>drawer.close();
drawer.addEventListener('close',()=>{$('openWatchlist').setAttribute('aria-expanded','false')});
drawer.addEventListener('click',event=>{if(event.target===drawer){const box=drawer.getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)drawer.close()}});

initMarketApiControls();

refreshFundamentals();
