let sourceRefreshBusy=false,sourceRefreshProgress='',sourceRefreshSummary='';
function marketApiBase(){let stored='';try{stored=localStorage.getItem('lucky-cat-api-url')||''}catch{}return (window.MARKET_API_URL||stored).replace(/\/$/,'')}
function cacheSourceData(){try{sessionStorage.setItem('lucky-cat-source-data',JSON.stringify(live))}catch{}}
function restoreSourceData(){try{const saved=JSON.parse(sessionStorage.getItem('lucky-cat-source-data')||'null');if(saved?.assets&&saved.generatedAt>live.generatedAt){live=saved;delete live.assets?.ALTINS1;delete live.errors?.ALTINS1;calcCache.clear();rankingCache=null}}catch{}}
function sourceEntry(payload,key){
 const result=payload.data?.chart?.result?.[0];if(!result?.timestamp)throw Error('Kaynak geçerli fiyat serisi döndürmedi.');
 const q=result.indicators?.quote?.[0],rows=[],seen=new Map();let omitted=0;
 result.timestamp.forEach((stamp,i)=>{const vals=['open','high','low','close'].map(k=>q?.[k]?.[i]);if(vals.some(v=>!Number.isFinite(v))){omitted++;return}const [o,h,l,c]=vals;const row={date:new Date(stamp*1000).toISOString().slice(0,10),o,h,l,c,v:Number.isFinite(q.volume?.[i])?q.volume[i]:null};if(Math.min(o,h,l,c)<=0||l>Math.min(o,c)||h<Math.max(o,c)){omitted++;return}seen.set(row.date,row)});
 rows.push(...[...seen.values()].sort((a,b)=>a.date.localeCompare(b.date)));if(rows.length<20||!validRows(rows))throw Error('Kullanılabilir ve tutarlı fiyat serisi yetersiz.');
 const meta=result.meta||{},now=payload.fetchedAt||new Date().toISOString();return {symbol:meta.symbol,currency:meta.currency,exchangeTimezone:meta.exchangeTimezoneName,rows,lastBar:rows.at(-1).date,source:'Yahoo Finance chart API',sourceUrl:`https://finance.yahoo.com/quote/${encodeURIComponent(meta.symbol||key)}/history/`,fetchedAt:now,checkedAt:now,quoteTime:meta.regularMarketTime,quotePrice:Number.isFinite(meta.regularMarketPrice)?meta.regularMarketPrice:null,quoteChangePercent:Number.isFinite(meta.regularMarketChangePercent)?meta.regularMarketChangePercent:null,validation:{receivedBars:result.timestamp.length,acceptedBars:rows.length,omittedBars:omitted,invalidOHLC:0,ohlcValid:true}};
}
function rebuildGram(){const gold=live.assets.XAUUSD,fx=live.assets.USDTRY;if(!gold||!fx||live.errors.XAUUSD||live.errors.USDTRY){live.errors.GRAMALTIN='Altın veya USD/TRY dayanağı yenilenemedi.';return}const rates=new Map(fx.rows.map(r=>[r.date,r])),rows=gold.rows.filter(g=>rates.has(g.date)).map(g=>{const f=rates.get(g.date),scale=31.1034768;return {date:g.date,o:g.o*f.o/scale,h:g.h*f.h/scale,l:g.l*f.l/scale,c:g.c*f.c/scale,v:null}});if(rows.length<20||!validRows(rows)){live.errors.GRAMALTIN='Türetilmiş seri tutarsız.';return}live.assets.GRAMALTIN={rows,lastBar:rows.at(-1).date,currency:'TRY',source:'Derived from gold futures and USD/TRY; indicative, not physical gram gold quote',sourceUrl:'https://finance.yahoo.com/markets/commodities/',fetchedAt:new Date().toISOString()};delete live.errors.GRAMALTIN}
async function refreshFromSource(){
 if(sourceRefreshBusy)return;const base=marketApiBase();if(!base){$('marketApiDialog').showModal();return}
 sourceRefreshBusy=true;sourceRefreshSummary='';let done=0,ok=0;const targets=current?(current==='GRAMALTIN'?['XAUUSD','USDTRY']:[current]):ALL.filter(s=>s!=='GRAMALTIN');let index=0;
 live.errors={...live.errors};sourceRefreshProgress=`0/${targets.length} varlık`;renderStatus('fetching');
 async function worker(){while(index<targets.length){const sym=targets[index++];try{const response=await fetch(`${base}/chart?symbol=${encodeURIComponent(sym)}&t=${Date.now()}`,{cache:'no-store',signal:AbortSignal.timeout(35000)});const payload=await response.json();if(!response.ok)throw Error(payload.error||`HTTP ${response.status}`);live.assets[sym]=sourceEntry(payload,sym);delete live.errors[sym];ok++}catch(error){live.errors[sym]=error.message||'Fiyat kaynağı okunamadı.'}finally{done++;sourceRefreshProgress=`${done}/${targets.length} varlık · ${ok} başarılı`;renderStatus('fetching')}}}
 try{await Promise.all(Array.from({length:Math.min(4,targets.length)},worker));if(!current||current==='GRAMALTIN'||['XAUUSD','USDTRY'].includes(current))rebuildGram();if(ok){live.generatedAt=new Date().toISOString();live.marketDataAsOf=Object.values(live.assets).map(e=>e.lastBar||'').sort().at(-1);cacheSourceData()}sourceRefreshSummary=`${ok}/${targets.length} varlık kaynaktan yenilendi${targets.length-ok?` · ${targets.length-ok} erişim sorunu`:''}.`;calcCache.clear();rankingCache=null;renderContent();renderStatus(ok?'source':'error',Date.now())}finally{sourceRefreshBusy=false;renderStatus(ok?'source':'error',Date.now())}
}
function initMarketApiControls(){restoreSourceData();renderContent();$('closeMarketApi').onclick=()=>$('marketApiDialog').close();$('marketApiUrl').value=marketApiBase();$('marketApiForm').addEventListener('submit',async event=>{event.preventDefault();const button=$('saveMarketApi');button.disabled=true;set('marketApiMessage','API bağlantısı kontrol ediliyor…');try{const url=new URL($('marketApiUrl').value.trim());if(url.protocol!=='https:')throw Error('API adresi https olmalı.');const base=url.href.replace(/\/$/,'');const response=await fetch(base+'/health',{cache:'no-store',signal:AbortSignal.timeout(10000)});const data=await response.json();if(!response.ok||!data.ok)throw Error('API sağlık kontrolü başarısız.');localStorage.setItem('lucky-cat-api-url',base);$('marketApiDialog').close();refreshFromSource()}catch(error){set('marketApiMessage',error.message)}finally{button.disabled=false}})}
