window.MARKET_CATALOG={
AEFES:['Anadolu Efes','İçecek','BIST 30','Satış hacmi ve fiyatlama gücü artarsa gelir ve faaliyet marjı iyileşebilir.','Hammadde maliyeti, vergi ve faaliyet gösterilen pazarlardaki kur oynaklığı marjı düşürebilir.','KAP faaliyet raporunda hacim, bölgesel satış, faaliyet marjı ve nakit akışı.'],
AKBNK:['Akbank','Bankacılık','BIST 30','Net faiz marjı ve ücret gelirleri artarken kredi kalitesi korunursa kârlılık güçlenebilir.','Fonlama maliyeti ve sorunlu kredi karşılıkları yükselirse kâr baskılanabilir.','KAP finansallarında net faiz geliri, karşılık gideri, takipteki kredi oranı ve sermaye yeterliliği.'],
ASELS:['ASELSAN','Savunma · teknoloji','BIST 30','Yeni sözleşmeler ve ihracat teslimatları gelir ile nakit üretimini destekleyebilir.','Siparişlerin gelire dönüşmesi gecikirse ve işletme sermayesi ihtiyacı artarsa değerleme baskılanabilir.','KAP finansallarında sipariş bakiyesi, satış, faaliyet kârı ve faaliyet nakit akışı.'],
ASTOR:['Astor Enerji','Elektrik ekipmanları','BIST 30','Trafo ve enerji altyapısı siparişleri artarsa kapasite ve ihracat büyümesi gelir yaratabilir.','Sipariş iptali, hammadde maliyeti ve kapasite yatırım giderleri marjı azaltabilir.','KAP sipariş açıklamaları, ihracat, brüt marj ve yatırım harcamaları.'],
BIMAS:['BİM','Perakende','BIST 30','Mağaza ağı ve aynı mağaza satışları büyürken giderler kontrol edilirse kârlılık artabilir.','Rekabet, ücret ve kira maliyetleri fiyatlama gücünü aşarsa marj daralabilir.','KAP mağaza sayısı, aynı mağaza büyümesi, brüt marj ve nakit akışı.'],
DSTKF:['Destek Faktoring','Finansal hizmetler','BIST 30','Faktoring işlem hacmi ve tahsilat kalitesi artarsa gelir büyüyebilir.','Müşteri temerrütleri ve finansman maliyetindeki artış özkaynağı zorlayabilir.','KAP faktoring alacakları, takipteki alacaklar, finansman maliyeti ve özkaynak.'],
EKGYO:['Emlak Konut GYO','Gayrimenkul','BIST 30','Konut satışları ve proje teslimleri hızlanırsa gelir ile nakit tahsilatı artabilir.','Yüksek faiz, zayıf konut talebi ve proje maliyeti nakit dönüşümünü geciktirebilir.','KAP ön satış, proje gelirleri, borç ve nakit akışı açıklamaları.'],
ENKAI:['Enka İnşaat','İnşaat · enerji','BIST 30','Yeni uluslararası projeler ve enerji operasyonları iş hacmini destekleyebilir.','Proje gecikmeleri, jeopolitik risk ve maliyet aşımları kârlılığı düşürebilir.','KAP iş portföyü, proje sözleşmeleri, enerji üretimi ve marjlar.'],
EREGL:['Ereğli Demir Çelik','Çelik','BIST 30','Çelik fiyatları ve iç talep toparlanırsa kapasite kullanımı ile marj artabilir.','Çin arzı, ithalat baskısı ve enerji maliyeti çelik marjını azaltabilir.','KAP tonaj, satış fiyatı, FAVÖK/ton ve yatırım harcamaları.'],
FROTO:['Ford Otosan','Otomotiv · ihracat','BIST 30','Avrupa ticari araç talebi ve ihracat artarsa üretim hacmi ile marj güçlenebilir.','Avrupa talep zayıflığı, üretim ve finansman maliyeti kârı baskılayabilir.','KAP üretim/ihracat adedi, faaliyet marjı ve nakit akışı.'],
GARAN:['Garanti BBVA','Bankacılık','BIST 30','Faiz marjı ve ücret gelirleri yükselirken kredi kalitesi korunursa kârlılık artabilir.','Kredi karşılıkları ve mevduat maliyeti artarsa özkaynak getirisi düşebilir.','KAP net faiz marjı, karşılık gideri, sorunlu kredi ve sermaye yeterliliği.'],
GUBRF:['Gübre Fabrikaları','Gübre · kimya','BIST 30','Gübre talebi ve üretim verimliliği artarsa operasyonel sonuçlar iyileşebilir.','Doğalgaz/hammadde fiyatı ve ithalat rekabeti marjı düşürebilir.','KAP üretim hacmi, hammadde gideri, brüt marj ve borç.'],
ISCTR:['İş Bankası C','Bankacılık','BIST 30','Net faiz geliri, komisyon ve aktif kalitesi iyileşirse kârlılık artabilir.','Mevduat maliyeti, kredi zarar karşılıkları ve düzenleme etkileri kârı azaltabilir.','KAP net faiz geliri, karşılıklar ve sermaye yeterliliği.'],
KCHOL:['Koç Holding','Holding','BIST 30','İştiraklerinin nakit üretimi ve net aktif değer iskontosunda daralma hisseyi destekleyebilir.','Enerji, otomotiv ve finans iştiraklerinde eş zamanlı yavaşlama değeri baskılayabilir.','KAP konsolide nakit akışı, iştirak kârları, net borç ve net aktif değer.'],
KRDMD:['Kardemir D','Çelik','BIST 30','Çelik talebi ve ürün fiyatları maliyetlerden hızlı artarsa marj yükselebilir.','Kok kömürü ve enerji maliyeti ile zayıf inşaat talebi marjı azaltabilir.','KAP satış tonajı, FAVÖK/ton, stok ve nakit akışı.'],
MGROS:['Migros','Perakende','BIST 30','Mağaza ve çevrim içi satış büyümesi ile tedarik verimliliği kârlılığı artırabilir.','Ücret, kira ve rekabet baskısı marjı zayıflatabilir.','KAP mağaza büyümesi, aynı mağaza satışları ve faaliyet nakit akışı.'],
PETKM:['Petkim','Petrokimya','BIST 30','Petrokimya ürün marjı ve talep toparlanırsa faaliyet sonucu iyileşebilir.','Nafta maliyeti, küresel arz fazlası ve zayıf talep zarar yaratabilir.','KAP ürün marjı, kapasite kullanımı, enerji/nafta maliyeti ve borç.'],
PGSUS:['Pegasus','Havacılık','BIST 30','Yolcu doluluğu ve yan gelirler birim maliyetten hızlı büyürse kârlılık güçlenebilir.','Yakıt, kur ve bilet fiyatı rekabeti marjları baskılayabilir.','KAP trafik verilerinde yolcu, doluluk; finansallarda birim gelir ve maliyet.'],
SAHOL:['Sabancı Holding','Holding','BIST 30','İştirak kârları ve net aktif değer iskontosunun daralması değer yaratabilir.','Banka ve enerji iştiraklerinde zayıf sonuçlar ile holding borcu riski artırabilir.','KAP iştirak kârları, net nakit/borç ve portföy değerlemesi.'],
SASA:['SASA Polyester','Kimya · polyester','BIST 30','Yeni kapasitenin dolması ve ürün marjının artması satışları büyütebilir.','Yüksek yatırım harcaması, borç ve küresel polyester arzı nakit akışını zorlayabilir.','KAP kapasite kullanımı, yatırım ilerlemesi, net borç ve nakit akışı.'],
SISE:['Şişecam','Cam · kimya','BIST 30','Cam talebi ve ihracat pazarları toparlanırsa kapasite kullanımı artabilir.','Enerji maliyeti ve zayıf inşaat/tüketim talebi marjları düşürebilir.','KAP segment satışları, enerji gideri, kapasite ve faaliyet marjı.'],
TAVHL:['TAV Havalimanları','Havalimanı işletmeciliği','BIST 30','Yolcu trafiği ve yolcu başına ticari gelir artarsa nakit üretimi güçlenebilir.','Yolcu talebi, imtiyaz harcaması ve finansman maliyeti kârı baskılayabilir.','KAP trafik verisi, yolcu başına gelir, imtiyaz yatırımı ve borç.'],
TCELL:['Turkcell','Telekomünikasyon','BIST 30','Mobil fiyatlama ve veri/dijital hizmet büyümesi gelir ile marjı destekleyebilir.','Yüksek şebeke yatırımı ve rekabet serbest nakit akışını sınırlayabilir.','KAP ARPU, abone, FAVÖK ve yatırım harcaması.'],
THYAO:['Türk Hava Yolları','Havacılık','BIST 30','Yolcu/kargo hacmi ve doluluk yükselirken birim gelir korunursa kâr artabilir.','Yakıt fiyatı, jeopolitik gelişmeler ve kur kaynaklı giderler marjı azaltabilir.','KAP trafik verisi, doluluk, yakıt gideri ve operasyonel kâr.'],
TOASO:['Tofaş','Otomotiv','BIST 30','Üretim ve iç pazar satışları toparlanırsa kapasite kullanımı ve kârlılık artabilir.','Otomobil talebi, finansman maliyeti ve model geçişi satışları yavaşlatabilir.','KAP üretim/satış adedi, kapasite, faaliyet marjı ve nakit.'],
TRALT:['Türk Altın İşletmeleri','Altın madenciliği','BIST 30','Altın fiyatı ve üretim hacmi yükselirken maliyet sabit kalırsa marj artabilir.','Maden operasyonu, izin, yatırım ve altın fiyatındaki düşüş nakit akışını azaltabilir.','KAP üretim miktarı, birim maliyet, rezerv ve yatırım harcamaları.'],
TTKOM:['Türk Telekom','Telekomünikasyon','BIST 30','Abone başına gelir büyür ve yatırım harcaması kontrol edilirse nakit üretimi artabilir.','Şebeke yatırımı, finansman maliyeti ve fiyat rekabeti nakit akışını baskılayabilir.','KAP ARPU, FAVÖK, yatırım harcaması ve nakit akışı.'],
TUPRS:['Tüpraş','Rafineri','BIST 30','Rafineri marjı ve ürün talebi güçlenirse faaliyet nakdi artabilir.','Petrol fiyatı oynaklığı, stok zararları ve düşen rafineri marjı kârı azaltabilir.','KAP rafineri marjı, kapasite kullanımı, stok etkisi ve nakit akışı.'],
VAKBN:['VakıfBank','Bankacılık','BIST 30','Net faiz marjı ve kredi kalitesi iyileşirse özkaynak kârlılığı yükselebilir.','Fonlama gideri ve kredi zarar karşılıkları artarsa kâr azalabilir.','KAP net faiz geliri, takipteki krediler, karşılıklar ve sermaye oranı.'],
YKBNK:['Yapı Kredi','Bankacılık','BIST 30','Faiz marjı ve kredi kalitesi iyileşirse dönem kârı artabilir.','Takipteki krediler ve fonlama maliyeti yükselirse marj baskılanabilir.','KAP net faiz geliri, karşılık gideri ve sermaye yeterliliği.'],
ARCLK:['Arçelik','Dayanıklı tüketim','Ek hisse','Talep ve üretim verimliliği toparlanırsa marj iyileşebilir.','Zayıf tüketim talebi ve finansman maliyeti kârlılığı düşürebilir.','KAP satış, brüt marj, net borç ve nakit akışı.'],
ALTINS1:['Darphane Altın Sertifikası','Altın sertifikası','Altın','Gram altının TL fiyatı yükselirse dayanak değeri artabilir.','Altın düşerse veya sertifikanın gram altına göre primi daralırsa fiyat gerileyebilir.','Borsa İstanbul ürün tanımı, sertifika fiyatı ve gram altın değeri arasındaki prim.'],
USDTRY:['Dolar / TL','Döviz','Döviz','Doların TL karşısında güçlenmesi kuru yükseltir.','TL faiz/getiri cazibesi ve döviz arzı artışı kuru sınırlayabilir.','TCMB gösterge kurları, enflasyon ve faiz kararları.'],
EURTRY:['Euro / TL','Döviz','Döviz','Euro/TL, hem USD/TL hem EUR/USD yükselişinden etkilenebilir.','TL güçlenmesi veya euronun dolara karşı zayıflaması kuru düşürebilir.','TCMB gösterge kurları; USD/TL ve EUR/USD eş zamanlı hareketi.'],
EURUSD:['Euro / Dolar','Döviz paritesi','Döviz','Euro Bölgesi beklentileri ABD’ye göre güçlenirse parite yükselebilir.','ABD faiz/getiri üstünlüğü doları güçlendirip pariteyi düşürebilir.','ECB ve Fed kararları ile tahvil getirileri.'],
XAUUSD:['Vadeli altın ons','Altın · USD/ons','Altın','Güvenli liman talebi ve reel faiz düşüşü ons altını destekleyebilir.','Reel faiz veya dolar güçlenirse ons altın gerileyebilir.','Vadeli altın fiyatı, ABD reel faizleri ve dolar endeksi.'],
GRAMALTIN:['Teorik gram altın · vadeli','Hesaplanan gösterge','Altın','Ons altın veya USD/TL yükselirse TL gram karşılığı artabilir.','Ons altın ve kur düşerse TL gram karşılığı azalabilir.','Ons USD × USD/TL ÷ 31,1034768 hesabı; kuyumcu alış/satış fiyatı değildir.'],
BRENT:['Brent petrol · vadeli','Petrol · USD/varil','Petrol','Küresel talep veya arz kesintisi Brent fiyatını yükseltebilir.','Zayıf talep ve üretim artışı fiyatı düşürebilir.','Vadeli Brent fiyatı, OPEC açıklamaları ve stok verileri.'],
WTI:['WTI petrol · vadeli','Petrol · USD/varil','Petrol','ABD talebi ve stok düşüşü WTI fiyatını destekleyebilir.','ABD stok artışı veya arz büyümesi fiyatı baskılayabilir.','WTI vadeli fiyatı ve ABD EIA haftalık stok verisi.']
};
// Membership is sourced independently from KAP; unresearched fundamentals stay explicit.
for (const [symbol,company] of Object.entries(window.MARKET_UNIVERSE?.companies||{})) {
  const group=window.MARKET_UNIVERSE.groups.XU030.includes(symbol)?'BIST 30':'BIST 100';
  if(window.MARKET_CATALOG[symbol])window.MARKET_CATALOG[symbol][2]=group;
  else window.MARKET_CATALOG[symbol]=[company.name,'BIST payı',group,'Bu şirket için finansal raporlara dayalı yükseliş tezi henüz doğrulanmadı. Teknik koşullar yukarıdaki fiyat serisinden hesaplanır.','Şirketin bilançosu ve güncel açıklamaları incelenmeden temel risklerin eksiksiz değerlendirildiği söylenemez.','KAP şirket bildirimleri ve finansal tablolarını kontrol edin. Haberler sekmesinde şirket adı/koduyla eşleşen başlıklar listelenir.'];
}
