function fairValue(sym){if(!STOCKS.includes(sym))return null;try{const data=JSON.parse(localStorage.getItem('lucky-cat-valuation-'+sym)||'null');if(!data||!['pe','pb'].includes(data.method)||!Number.isFinite(data.base)||!Number.isFinite(data.multiple)||data.base<=0||data.multiple<=0||!data.period||!data.source)return null;const value=data.base*data.multiple;return Number.isFinite(value)?{...data,value}:null}catch{return null}}
function renderFairValue(){const value=fairValue(current),x=calc(current),stock=STOCKS.includes(current);set('fair',value?formatPrice(current,value.value):'—');set('fairText',!stock?'Hisseler için kullanılır':value&&x?.fresh?`Mevcut fiyatın %${fmt(Math.abs(value.value/x.last.c-1)*100,1)} ${value.value>=x.last.c?'üzerinde':'altında'} · tahmin`:value?'Kaydedilmiş tahmin':'Hesaplamak için dokun')}
function openFairValue(){if(!current)return;const stock=STOCKS.includes(current),record=fairValue(current),x=calc(current);set('metricDialogTag','BASİT DEĞER HESABI');set('metricDialogTitle',`${current} · Adil değer`);
 const difference=record&&x?(record.value/x.last.c-1)*100:null;
 $('metricDialogBody').innerHTML=!stock?'<p class="bodyText">Bu hesap şirket hisseleri içindir. Altın, petrol ve döviz için kullanılmaz.</p>':`<p class="bodyText">Bir hissenin yaklaşık değerini hesapla. Şirketin finansal verileri henüz otomatik gelmiyor; aşağıdaki iki sayıyı sen giriyorsun.</p>${record?`<div class="valuationResult"><span>Tahmini değer</span><strong>${formatPrice(current,record.value)}</strong><div class="simpleValueCompare"><div><small>Mevcut fiyat</small><b>${x?formatPrice(current,x.last.c):'—'}</b></div><div><small>Tahminle karşılaştırma</small><b>${difference===null?'Fiyat yok':`Tahmin %${fmt(Math.abs(difference),1)} ${difference>=0?'daha yüksek':'daha düşük'}`}</b></div></div><p>Bu fark, fiyatın oraya ulaşacağını veya o kadar kazanç sağlayacağını göstermez.</p></div>`:'<div class="simpleValueIntro"><strong>Nasıl çalışıyor?</strong><p>Hisse başına yıllık kâr × seçtiğin kâr katı = tahmini değer.</p><small>Sadece örnek: 10 TL kâr × 12 kat = 120 TL. Bu sayılar bu şirketin verisi veya önerilen değerler değildir.</small></div>'}
 <form id="fairValueForm" class="valuationForm simpleValuation"><label><span id="valuationBaseLabel">1. Bir hissenin yıllık kârı kaç TL?</span><input name="base" type="number" min="0.000001" step="any" required value="${record?.base??''}" placeholder="Hisse başına tutarı gir"><small id="valuationBaseHelp">Şirketin son 12 aylık hisse başına kârı. Toplam şirket kârını buraya yazma.</small></label><label><span id="valuationMultipleLabel">2. Bu kârın kaç katını değer olarak alalım?</span><input name="multiple" type="number" min="0.000001" step="any" required value="${record?.multiple??''}" placeholder="Kullanmak istediğin katı gir"><small id="valuationMultipleHelp">Örneğin 12 yazarsan kârı 12 ile çarparız. Bu katsayı senin varsayımın.</small></label>
 <details class="valuationAdvanced"><summary>Hesap yöntemini değiştir / kaynak ekle</summary><label>Yöntem<select name="method"><option value="pe" ${record?.method==='pe'?'selected':''}>Yıllık kâra göre</option><option value="pb" ${record?.method==='pb'?'selected':''}>Şirketin özkaynağına göre</option></select></label><label>Verinin dönemi (isteğe bağlı)<input name="period" maxlength="80" value="${esc(record?.period==='Belirtilmedi'?'':record?.period||'')}" placeholder="Ör. son 12 ay / 2026 2Ç"></label><label>Veriyi nereden aldın? (isteğe bağlı)<input name="source" maxlength="500" value="${esc(record?.source==='Kullanıcı girdisi'?'':record?.source||'')}" placeholder="Rapor adı veya bağlantısı"></label><p class="sourceNote">Özkaynak yönteminde hisse başına defter değeri × seçtiğin kat kullanılır. Negatif kâr veya özkaynakta bu basit hesap uygulanmaz. Borç, büyüme ve tek seferlik gelirler ayrıca değerlendirilmelidir.</p></details>
 <div class="valuationActions"><button class="primaryLink" type="submit">Tahmini değeri hesapla</button><button id="clearFairValue" class="smallBtn" type="button">Hesabı sıfırla</button></div><p id="fairValueMessage" role="status"></p><p class="sourceNote">Girdiler doğrulanmış finansal veri sayılmaz. Hesabın yalnız bu tarayıcıda, bu hisse için saklanır. Teknik puanı değiştirmez.</p></form>`;
 $('metricDialog').showModal();if(!stock)return;
 const form=$('fairValueForm'),method=form.elements.namedItem('method');
 function explainMethod(){const pb=method.value==='pb';set('valuationBaseLabel',pb?'1. Bir hissenin defter değeri kaç TL?':'1. Bir hissenin yıllık kârı kaç TL?');set('valuationBaseHelp',pb?'Şirketin özkaynağı / aynı tarihteki toplam hisse adedi. Toplam özkaynağı buraya yazma.':'Şirketin son 12 aylık hisse başına kârı. Toplam şirket kârını buraya yazma.');set('valuationMultipleLabel',pb?'2. Defter değerinin kaç katını kullanalım?':'2. Bu kârın kaç katını değer olarak alalım?');set('valuationMultipleHelp',pb?'Örneğin 1,5 yazarsan defter değerini 1,5 ile çarparız. Bu katsayı senin varsayımın.':'Örneğin 12 yazarsan kârı 12 ile çarparız. Bu katsayı senin varsayımın.')}
 explainMethod();method.addEventListener('change',()=>{form.elements.namedItem('base').value='';form.elements.namedItem('multiple').value='';explainMethod()});
 form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form),base=Number(data.get('base')),multiple=Number(data.get('multiple'));if(!Number.isFinite(base*multiple)||base<=0||multiple<=0){set('fairValueMessage','İki alana da sıfırdan büyük bir sayı gir.');return}try{localStorage.setItem('lucky-cat-valuation-'+current,JSON.stringify({method:data.get('method'),base,multiple,period:String(data.get('period')).trim()||'Belirtilmedi',source:String(data.get('source')).trim()||'Kullanıcı girdisi',savedAt:new Date().toISOString()}));renderDetail();$('metricDialog').close();openFairValue()}catch{set('fairValueMessage','Tarayıcı hesabı kaydetmeye izin vermedi.')}});
 $('clearFairValue').onclick=()=>{try{localStorage.removeItem('lucky-cat-valuation-'+current);renderDetail();$('metricDialog').close();openFairValue()}catch{set('fairValueMessage','Kayıt kaldırılamadı.')}};
}
