let fundamentals={companies:[],generated_at:null},fundamentalError='',fundamentalBusy=false;
function fairValue(){return null}
function fundamentalCompany(sym){return fundamentals.companies.find(c=>c.ticker===sym)}
function ratioCell(value){return Number.isFinite(value)?fmt(value,2):'—'}
function valuationTable(symbols){return `<div class="valuationTableScroll"><table class="multiplesTable"><thead><tr><th rowspan="2">HİSSE</th><th colspan="2">F/K</th><th colspan="2">FD/FAVÖK</th><th colspan="2">PD/DD</th></tr><tr>${Array(3).fill('<th>Güncel</th><th>3 yıllık ort.</th>').join('')}</tr></thead><tbody>${symbols.map(sym=>{const c=fundamentalCompany(sym);return `<tr><td><a href="#varlik/${sym}"><span class="companyCoin">${esc(sym.slice(0,2))}</span><span><b>${esc(sym)}</b><small>${esc(CAT[sym]?.[0]||sym)}</small></span></a></td>${['pe','ev_ebitda','pb'].map(k=>`<td>${ratioCell(c?.[k])}</td><td class="unavailable" title="Kaynak tarihsel fiyat çarpanı sağlamıyor">—</td>`).join('')}</tr>`}).join('')}</tbody></table></div>`}
function valuationSection(){return `<section class="panel historicalValuation"><span class="eyebrow">OTOMATİK TEMEL ANALİZ</span><h3>Şirketlerin değerleme çarpanları</h3><p>F/K, FD/FAVÖK ve PD/DD · Güncel ve üç yıllık ortalama karşılaştırması</p><p class="valuationAvailability">${fundamentalBusy?'Finansal veriler alınıyor…':fundamentalError?esc(fundamentalError):'Üç yıllık fiyat çarpanı serisi kaynakta bulunmadığı için tarihsel ortalama ve adil değer hesaplanamıyor. Bu liste bir ucuzluk sıralaması değildir.'}</p>${valuationTable(STOCKS)}${valuationSource()}</section>`}
function valuationSource(){return `<p class="sourceNote">Veri: KAP/Borsa İstanbul, derleyen <a href="https://bilancoveri.com/api/" target="_blank" rel="noopener noreferrer">BilancoVeri.com</a> · Kaynak üretimi: ${fundamentals.generated_at?esc(timeText(fundamentals.generated_at)):'henüz alınmadı'}. Çarpanlar kaynağın fiyatına aittir; canlı fiyatla karıştırılmaz. Fiyatlar en az 15 dakika gecikmelidir.</p>`}
function renderFairValue(){set('fair','—');set('fairText',STOCKS.includes(current)?'Tarihsel veri eksik · ayrıntıları gör':'Hisseler için kullanılır')}
function openFairValue(){if(!current)return;set('metricDialogTag','OTOMATİK DEĞERLEME');set('metricDialogTitle',`${current} · Adil değer`);const c=fundamentalCompany(current);$('metricDialogBody').innerHTML=!STOCKS.includes(current)?'<p>Şirket çarpanları altın, petrol ve döviz için uygulanmaz.</p>':`<div class="valuationResult"><span>Otomatik adil değer tahmini</span><strong>Hesaplanamıyor</strong><p>Üç yıllık doğrulanmış çarpan geçmişi eksik. Fiyat ortalaması adil değer yerine kullanılmaz.</p></div>${valuationTable([current])}<div class="metricDialogGrid"><div><span>Kaynağın referans fiyatı</span><b>${c?formatPrice(current,c.price):'—'}</b></div><div><span>Finansal dönem</span><b>${esc(c?.last_period||'—')}</b></div></div><h3>Otomatik hesap nasıl yapılacak?</h3><p>F/K yönteminde son 12 aylık hisse başına kâr × üç yıllık ortalama F/K; PD/DD yönteminde hisse başına özkaynak × üç yıllık ortalama PD/DD kullanılır. FD/FAVÖK yönteminde firma değerinden net borç çıkarılıp hisse adedine bölünür. Bankalarda FD/FAVÖK kullanılmaz.</p><p>Negatif kâr, eksik dönemler, sermaye değişiklikleri ve enflasyon muhasebesi kontrol edilmeden sonuç üretilmez. Hesaplanan değer kesin olması gereken fiyat veya getiri garantisi değildir.</p>${valuationSource()}`;$('metricDialog').showModal()}
async function refreshFundamentals(){if(fundamentalBusy)return;fundamentalBusy=true;try{const response=await fetch('https://bilancoveri.com/api/v1/sirketler.json',{cache:'no-cache',signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error(`HTTP ${response.status}`);const data=await response.json();if(!Array.isArray(data.companies)||!data.generated_at)throw Error('Geçersiz finansal veri');fundamentals=data;fundamentalError='';}catch(error){fundamentalError='Finansal kaynak alınamadı: '+error.message;}finally{fundamentalBusy=false;render();}}
